// @generated by Metrics Storybook story generator
// @source-hash: e923bf49eb2372e9

// TODO(story): Provide representative values for required props:
// - table: Table<TData>
import type { Meta, StoryObj } from "@storybook/react-vite";

import { DataGridColumnVisibility } from "./data-grid-column-visibility";

const meta = {
  title: "Primitives/Data Grid/Data Grid Column Visibility",
  component: DataGridColumnVisibility,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {
    trigger: "Trigger",
  },
} satisfies Meta<typeof DataGridColumnVisibility>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
