// @generated by Metrics Storybook story generator
// @source-hash: 05f3954c4d4dfbb8

import type { Meta, StoryObj } from "@storybook/react-vite";

import { DataGridTable } from "./data-grid-table";

const meta = {
  title: "Primitives/Data Grid/Data Grid Table",
  component: DataGridTable,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof DataGridTable>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
