// @generated by Metrics Storybook story generator
// @source-hash: ff5f21a7df7b45d3

import type { Meta, StoryObj } from "@storybook/react";

import { DataGridPagination } from "./data-grid-pagination";

const meta = {
  title: "Primitives/Data Grid/Data Grid Pagination",
  component: DataGridPagination,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof DataGridPagination>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
