// @generated by Metrics Storybook story generator
// @source-hash: 63904b476e622980

import type { Meta, StoryObj } from "@storybook/react-vite";

import { DataGridTableDndRowHandle } from "./data-grid-table-dnd-rows";

const meta = {
  title: "Primitives/Data Grid/Data Grid Table Dnd Row Handle",
  component: DataGridTableDndRowHandle,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof DataGridTableDndRowHandle>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
