// @generated by Metrics Storybook story generator
// @source-hash: 199dc58f9784f690

import type { Meta, StoryObj } from "@storybook/react-vite";

import { DataGridTableDnd } from "./data-grid-table-dnd";

const meta = {
  title: "Primitives/Data Grid/Data Grid Table Dnd",
  component: DataGridTableDnd,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {
    handleDragEnd: () => {},
  },
} satisfies Meta<typeof DataGridTableDnd>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
