// @generated by Metrics Storybook story generator
// @source-hash: a32c3c11cc47bb6a

import type { Meta, StoryObj } from "@storybook/react";

import { DataGridColumnFilter } from "./data-grid-column-filter";

const meta = {
  title: "Primitives/Data Grid/Data Grid Column Filter",
  component: DataGridColumnFilter,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {
    options: "Options",
  },
} satisfies Meta<typeof DataGridColumnFilter>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
