// @generated by Metrics Storybook story generator
// @source-hash: cbc9411171c89fda

// TODO(story): Provide representative values for required props:
// - table: Table<TData>
import type { Meta, StoryObj } from "@storybook/react";

import { DataGridProvider } from "./data-grid";

const meta = {
  title: "Primitives/Data Grid/Data Grid Provider",
  component: DataGridProvider,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {
    recordCount: 1,
    children: "Data Grid Provider",
  },
} satisfies Meta<typeof DataGridProvider>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
