// @generated by Metrics Storybook story generator
// @source-hash: c9e653e1f51b5513

import type { Meta, StoryObj } from "@storybook/react";

import { AddToCursor } from "./add-to-cursor";

const meta = {
  title: "Primitives/Registry/Add To Cursor",
  component: AddToCursor,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {
    mcp: "Mcp",
  },
} satisfies Meta<typeof AddToCursor>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
