// @generated by Metrics Storybook story generator
// @source-hash: cabeddb30ce133c2

// TODO(story): Provide representative values for required props:
// - component: Component
import type { Meta, StoryObj } from "@storybook/react-vite";

import { ComponentCard } from "./component-card";

const meta = {
  title: "Primitives/Registry/Component Card",
  component: ComponentCard,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {
    baseUrl: "Base Url",
    prompt: "Prompt",
  },
} satisfies Meta<typeof ComponentCard>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
