// @generated by Metrics Storybook story generator
// @source-hash: cd06b413030ed726

import type { Meta, StoryObj } from "@storybook/react-vite";

import { MCPTabs } from "./mcp-tabs";

const meta = {
  title: "Primitives/Registry/MCPTabs",
  component: MCPTabs,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {
    rootUrl: "Root Url",
  },
} satisfies Meta<typeof MCPTabs>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
