// @generated by Metrics Storybook story generator
// @source-hash: ae6f38029d8fb6e5

import type { Meta, StoryObj } from "@storybook/react-vite";

import { OpenInV0Button } from "./open-in-v0";

const meta = {
  title: "Primitives/Registry/Open In V0 Button",
  component: OpenInV0Button,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {
    registryUrl: "Registry Url",
  },
} satisfies Meta<typeof OpenInV0Button>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
