// @generated by Metrics Storybook story generator
// @source-hash: a5f194d9637a80ec

import type { Meta, StoryObj } from "@storybook/react-vite";

import { RegistrySidebar } from "./registry-sidebar";

const meta = {
  title: "Primitives/Registry/Registry Sidebar",
  component: RegistrySidebar,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof RegistrySidebar>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
