// @generated by Metrics Storybook story generator
// @source-hash: b1477e5874307768

import type { Meta, StoryObj } from "@storybook/react";

import { RegistryLogo } from "./registry-logo";

const meta = {
  title: "Primitives/Registry/Registry Logo",
  component: RegistryLogo,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof RegistryLogo>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
