// @generated by Metrics Storybook story generator
// @source-hash: 684aa940904eac5f

import type { Meta, StoryObj } from "@storybook/react";

import { ModeToggle } from "./theme-toggle";

const meta = {
  title: "Primitives/Registry/Mode Toggle",
  component: ModeToggle,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ModeToggle>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
