// @generated by Metrics Storybook story generator
// @source-hash: 37b34b6bd29cc44a

// TODO(story): Provide representative values for required props:
// - item: z.ZodArray<any> | z.ZodDefault<any>
// - form: ReturnType<typeof useForm>
import type { Meta, StoryObj } from "@storybook/react";

import { AutoFormArray } from "./array";

const meta = {
  title: "Primitives/Forms/Fields/Auto Form Array",
  component: AutoFormArray,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {
    name: "Name",
  },
} satisfies Meta<typeof AutoFormArray>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
