// @generated by Metrics Storybook story generator
// @source-hash: c429115e9fb59a04

import type { Meta, StoryObj } from "@storybook/react";

import { AutoFormCheckbox } from "./checkbox";

const meta = {
  title: "Primitives/Forms/Fields/Auto Form Checkbox",
  component: AutoFormCheckbox,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof AutoFormCheckbox>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
