// @generated by Metrics Storybook story generator
// @source-hash: 2c1bf30d066736db

import type { Meta, StoryObj } from "@storybook/react";

import { AutoFormDate } from "./date";

const meta = {
  title: "Primitives/Forms/Fields/Auto Form Date",
  component: AutoFormDate,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof AutoFormDate>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
