// @generated by Metrics Storybook story generator
// @source-hash: 025880fe75ad76e0

import type { Meta, StoryObj } from "@storybook/react";

import { AutoFormEnum } from "./enum";

const meta = {
  title: "Primitives/Forms/Fields/Auto Form Enum",
  component: AutoFormEnum,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof AutoFormEnum>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
