// @generated by Metrics Storybook story generator
// @source-hash: 43a242eaa7e2f600

import type { Meta, StoryObj } from "@storybook/react-vite";

import { Field } from "./field";

const meta = {
  title: "Primitives/Forms/Fields/Field",
  component: Field,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof Field>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
