// @generated by Metrics Storybook story generator
// @source-hash: 5437d60d6a95df9c

import type { Meta, StoryObj } from "@storybook/react";

import { FieldGroupExample } from "./field-group";

const meta = {
  title: "Primitives/Forms/Fields/Field Group Example",
  component: FieldGroupExample,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof FieldGroupExample>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
