// @generated by Metrics Storybook story generator
// @source-hash: ff3525287bb6c275

import type { Meta, StoryObj } from "@storybook/react";

import { FormItem } from "./form";

const meta = {
  title: "Primitives/Forms/Fields/Form Item",
  component: FormItem,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof FormItem>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
