// @generated by Metrics Storybook story generator
// @source-hash: 9ec3810e4f4671e0

import type { Meta, StoryObj } from "@storybook/react";

import { AutoFormInput } from "./input";

const meta = {
  title: "Primitives/Forms/Fields/Auto Form Input",
  component: AutoFormInput,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof AutoFormInput>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
