// @generated by Metrics Storybook story generator
// @source-hash: 93a65cab22d501f0

import type { Meta, StoryObj } from "@storybook/react";

import { AutoFormNumber } from "./number";

const meta = {
  title: "Primitives/Forms/Fields/Auto Form Number",
  component: AutoFormNumber,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof AutoFormNumber>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
