// @generated by Metrics Storybook story generator
// @source-hash: b19f77f804b3c227

// TODO(story): Provide representative values for required props:
// - schema: SchemaType | z.ZodType<z.infer<SchemaType>>
// - form: ReturnType<typeof useForm>
import type { Meta, StoryObj } from "@storybook/react-vite";

import { AutoFormObject } from "./object";

const meta = {
  title: "Primitives/Forms/Fields/Auto Form Object",
  component: AutoFormObject,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof AutoFormObject>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
