// @generated by Metrics Storybook story generator
// @source-hash: fe0a50393a587736

import type { Meta, StoryObj } from "@storybook/react";

import { AutoFormRadioGroup } from "./radio-group";

const meta = {
  title: "Primitives/Forms/Fields/Auto Form Radio Group",
  component: AutoFormRadioGroup,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof AutoFormRadioGroup>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
