// @generated by Metrics Storybook story generator
// @source-hash: 18ed941ae6c1aa30

import type { Meta, StoryObj } from "@storybook/react";

import { AutoFormSwitch } from "./switch";

const meta = {
  title: "Primitives/Forms/Fields/Auto Form Switch",
  component: AutoFormSwitch,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof AutoFormSwitch>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
