// @generated by Metrics Storybook story generator
// @source-hash: fa9c300fcbd0111b

import type { Meta, StoryObj } from "@storybook/react-vite";

import { AutoFormTextarea } from "./textarea";

const meta = {
  title: "Primitives/Forms/Fields/Auto Form Textarea",
  component: AutoFormTextarea,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof AutoFormTextarea>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
