// @generated by Metrics Storybook story generator
// @source-hash: bf8c9acbc5ea2a21

import type { Meta, StoryObj } from "@storybook/react-vite";

import { HelpDeskDocumentationPage } from "./documentation_page";

const meta = {
  title: "Components/Metrics Layouts/Help Desk/Help Desk Documentation Page",
  component: HelpDeskDocumentationPage,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof HelpDeskDocumentationPage>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
