// @generated by Metrics Storybook story generator
// @source-hash: b7f2b1aa814c3665

import type { Meta, StoryObj } from "@storybook/react";

import { BrandHeader } from "./brand-header";

const meta = {
  title: "Primitives/Layouts/Brand Header",
  component: BrandHeader,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof BrandHeader>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
