// @generated by Metrics Storybook story generator
// @source-hash: e9803a827d726bad

import type { Meta, StoryObj } from "@storybook/react-vite";

import { BrandSidebar } from "./brand-sidebar";

const meta = {
  title: "Primitives/Layouts/Brand Sidebar",
  component: BrandSidebar,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof BrandSidebar>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
