// @generated by Metrics Storybook story generator
// @source-hash: f1413a96aaa76a51

import type { Meta, StoryObj } from "@storybook/react";

import { ComingSoon } from "./coming-soon";

const meta = {
  title: "Primitives/Layouts/Coming Soon",
  component: ComingSoon,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ComingSoon>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
