// @generated by Metrics Storybook story generator
// @source-hash: 75257b49e8ac8628

import type { Meta, StoryObj } from "@storybook/react";

import { Hero } from "./hero";

const meta = {
  title: "Primitives/Layouts/Hero",
  component: Hero,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {
    title: "Title",
    description: "Description",
    buttonText: "Button Text",
    buttonLink: "Button Link",
    backgroundImage: "Background Image",
  },
} satisfies Meta<typeof Hero>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
