// @generated by Metrics Storybook story generator
// @source-hash: de3a44d993a974a8

// TODO(story): Provide representative values for required props:
// - as: T
import type { Meta, StoryObj } from "@storybook/react";

import { MeasuredContainer } from "./measured-container";

const meta = {
  title: "Primitives/Layouts/Measured Container",
  component: MeasuredContainer,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {
    name: "Name",
    children: "Measured Container",
  },
} satisfies Meta<typeof MeasuredContainer>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
