// @generated by Metrics Storybook story generator
// @source-hash: 36792e0de5d78c34

import type { Meta, StoryObj } from "@storybook/react-vite";

import { NavigationMenu } from "./navigation-menu";

const meta = {
  title: "Primitives/Layouts/Navigation Menu",
  component: NavigationMenu,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof NavigationMenu>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
