// @generated by Metrics Storybook story generator
// @source-hash: 914e99a6a8c61593

import type { Meta, StoryObj } from "@storybook/react-vite";

import { NavigationProgress } from "./navigation-progress";

const meta = {
  title: "Primitives/Layouts/Navigation Progress",
  component: NavigationProgress,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof NavigationProgress>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
