// @generated by Metrics Storybook story generator
// @source-hash: fbc54e92da039362

import type { Meta, StoryObj } from "@storybook/react-vite";

import { ResizableVertical } from "./resizable-vertical";

const meta = {
  title: "Primitives/Layouts/Resizable Vertical",
  component: ResizableVertical,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ResizableVertical>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
