// @generated by Metrics Storybook story generator
// @source-hash: d0ea33471c08b265

import type { Meta, StoryObj } from "@storybook/react";

import { ResizableHandleDemo } from "./resizable-handle";

const meta = {
  title: "Primitives/Layouts/Resizable Handle Demo",
  component: ResizableHandleDemo,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ResizableHandleDemo>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
