// @generated by Metrics Storybook story generator
// @source-hash: 1039944869ab913b

import type { Meta, StoryObj } from "@storybook/react-vite";

import { Sidebar } from "./sidebar";

const meta = {
  title: "Primitives/Layouts/Sidebar",
  component: Sidebar,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof Sidebar>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
