// @generated by Metrics Storybook story generator
// @source-hash: 139dc780c5ff5527

import type { Meta, StoryObj } from "@storybook/react";

import { SubNav } from "./sub-nav";

const meta = {
  title: "Primitives/Layouts/Sub Nav",
  component: SubNav,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof SubNav>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
