// @generated by Metrics Storybook story generator
// @source-hash: f4e0cc944d270e92

// TODO(story): Provide representative values for required props:
// - sections: { [key in SectionKey]: ReactNode; }
import type { Meta, StoryObj } from "@storybook/react-vite";

import { SwapLayout } from "./swap-layout";

const meta = {
  title: "Primitives/Layouts/Swap Layout",
  component: SwapLayout,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {
    sectionSlotClassNames: "Section Slot Class Names",
    defaultEditing: false,
  },
} satisfies Meta<typeof SwapLayout>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
