// @generated by Metrics Storybook story generator
// @source-hash: e29666994f220741

import type { Meta, StoryObj } from "@storybook/react-vite";

import { SwapLayoutLoader } from "./swap-layout-loader";

const meta = {
  title: "Primitives/Layouts/Swap Layout Loader",
  component: SwapLayoutLoader,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof SwapLayoutLoader>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
