// @generated by Metrics Storybook story generator
// @source-hash: 0af11ed12e6b2355

import type { Meta, StoryObj } from "@storybook/react-vite";

import { SkeletonAvatar } from "./skeleton-avatar";

const meta = {
  title: "Primitives/Skeleton/Skeleton Avatar",
  component: SkeletonAvatar,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof SkeletonAvatar>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
