// @generated by Metrics Storybook story generator
// @source-hash: 77218866b440a3c5

import type { Meta, StoryObj } from "@storybook/react";

import { SkeletonDemo } from "./skeleton-demo";

const meta = {
  title: "Primitives/Skeleton/Skeleton Demo",
  component: SkeletonDemo,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof SkeletonDemo>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
