// @generated by Metrics Storybook story generator
// @source-hash: 10ae27f00211cfde

import type { Meta, StoryObj } from "@storybook/react-vite";

import { SkeletonCard } from "./skeleton-card";

const meta = {
  title: "Primitives/Skeleton/Skeleton Card",
  component: SkeletonCard,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof SkeletonCard>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
