// @generated by Metrics Storybook story generator
// @source-hash: 49047a47037cd395

import type { Meta, StoryObj } from "@storybook/react-vite";

import { SkeletonForm } from "./skeleton-form";

const meta = {
  title: "Primitives/Skeleton/Skeleton Form",
  component: SkeletonForm,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof SkeletonForm>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
