// @generated by Metrics Storybook story generator
// @source-hash: 69b68a3be4d82c4d

import type { Meta, StoryObj } from "@storybook/react-vite";

import { SkeletonText } from "./skeleton-text";

const meta = {
  title: "Primitives/Skeleton/Skeleton Text",
  component: SkeletonText,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof SkeletonText>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
