// @generated by Metrics Storybook story generator
// @source-hash: 628344f75f0c3e52

import type { Meta, StoryObj } from "@storybook/react-vite";

import { SkeletonTable } from "./skeleton-table";

const meta = {
  title: "Primitives/Skeleton/Skeleton Table",
  component: SkeletonTable,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof SkeletonTable>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
