#!/usr/bin/env node

import { createHash } from "node:crypto";
import { existsSync } from "node:fs";
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import ts from "typescript";

const GENERATED = "// @generated by Metrics Storybook story generator";
const HASH_PREFIX = "// @source-hash: ";
const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(scriptDir, "../../..");
const uiRoot = resolve(repoRoot, "packages/ui/src");
const defaultRoots = [
  resolve(uiRoot, "primitives"),
  resolve(uiRoot, "components"),
];

const ignoredDirs = new Set([
  "node_modules",
  "dist",
  "build",
  ".next",
  "storybook-static",
  "__tests__",
  "fixtures",
  "demo",
  "generated",
]);

function posix(value) {
  return value.split(sep).join("/");
}

function hash(value) {
  return createHash("sha256").update(value).digest("hex").slice(0, 16);
}

function parseArgs(argv) {
  const options = {
    check: false,
    dryRun: false,
    force: false,
    folder: null,
    component: null,
    report: "apps/storybook/story-generation-report.json",
  };

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === "--check") options.check = true;
    else if (arg === "--dry-run") options.dryRun = true;
    else if (arg === "--force") options.force = true;
    else if (arg === "--folder") options.folder = argv[++index] ?? null;
    else if (arg === "--component") options.component = argv[++index] ?? null;
    else if (arg === "--report") options.report = argv[++index] ?? options.report;
    else if (arg === "--help" || arg === "-h") {
      console.log(`Usage: node apps/storybook/scripts/generate-stories.mjs [options]\n\n--check\n--dry-run\n--force\n--folder <path>\n--component <name>\n--report <path>`);
      process.exit(0);
    } else {
      throw new Error(`Unknown option: ${arg}`);
    }
  }

  return options;
}

function shouldSkipFile(filePath) {
  const normalized = posix(filePath);
  return (
    !/\.(tsx|jsx)$/.test(normalized) ||
    /\.(stories|test|spec)\.(tsx|jsx)$/.test(normalized) ||
    /\/index\.(tsx|jsx)$/.test(normalized) ||
    /\/metadata\.(tsx|jsx)$/.test(normalized)
  );
}

async function walk(directory) {
  if (!existsSync(directory)) return [];
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    const fullPath = resolve(directory, entry.name);
    if (entry.isDirectory()) {
      if (!ignoredDirs.has(entry.name)) files.push(...(await walk(fullPath)));
    } else if (entry.isFile() && !shouldSkipFile(fullPath)) {
      files.push(fullPath);
    }
  }

  return files;
}

function hasExportModifier(node) {
  return Boolean(node.modifiers?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword));
}

function componentName(name) {
  return /^[A-Z][A-Za-z0-9]*$/.test(name);
}

function returnsJsx(node) {
  let found = false;
  const visit = (child) => {
    if (
      ts.isJsxElement(child) ||
      ts.isJsxSelfClosingElement(child) ||
      ts.isJsxFragment(child)
    ) {
      found = true;
      return;
    }
    if (!found) ts.forEachChild(child, visit);
  };
  if (node.body) ts.forEachChild(node.body, visit);
  return found;
}

function variableLooksLikeComponent(node) {
  const init = node.initializer;
  if (!init) return false;
  if (ts.isArrowFunction(init) || ts.isFunctionExpression(init)) return true;
  if (ts.isCallExpression(init)) {
    return /(forwardRef|memo)$/.test(init.expression.getText());
  }
  return false;
}

function collectDeclarations(sourceFile) {
  const declarations = new Map();
  const exported = new Set();

  for (const statement of sourceFile.statements) {
    if (ts.isFunctionDeclaration(statement) && statement.name) {
      declarations.set(statement.name.text, statement);
      if (hasExportModifier(statement)) exported.add(statement.name.text);
    }

    if (ts.isClassDeclaration(statement) && statement.name) {
      declarations.set(statement.name.text, statement);
      if (hasExportModifier(statement)) exported.add(statement.name.text);
    }

    if (ts.isVariableStatement(statement)) {
      for (const declaration of statement.declarationList.declarations) {
        if (ts.isIdentifier(declaration.name)) {
          declarations.set(declaration.name.text, declaration);
          if (hasExportModifier(statement)) exported.add(declaration.name.text);
        }
      }
    }

    if (
      ts.isExportDeclaration(statement) &&
      statement.exportClause &&
      ts.isNamedExports(statement.exportClause) &&
      !statement.moduleSpecifier
    ) {
      for (const element of statement.exportClause.elements) {
        exported.add(element.name.text);
      }
    }
  }

  return { declarations, exported };
}

function isComponentDeclaration(node) {
  if (!node) return false;
  if (ts.isFunctionDeclaration(node)) return returnsJsx(node);
  if (ts.isVariableDeclaration(node)) return variableLooksLikeComponent(node);
  if (ts.isClassDeclaration(node)) {
    return Boolean(
      node.heritageClauses?.some((clause) =>
        clause.types.some((type) => /(Component|PureComponent)/.test(type.expression.getText())),
      ),
    );
  }
  return false;
}

function propsTypeNode(declaration) {
  if (!declaration) return null;
  if (ts.isFunctionDeclaration(declaration)) return declaration.parameters[0]?.type ?? null;
  if (ts.isVariableDeclaration(declaration)) {
    const init = declaration.initializer;
    if (init && (ts.isArrowFunction(init) || ts.isFunctionExpression(init))) {
      return init.parameters[0]?.type ?? null;
    }
    if (init && ts.isCallExpression(init)) return init.typeArguments?.[0] ?? null;
  }
  return null;
}

function collectLocalTypes(sourceFile) {
  const map = new Map();
  for (const statement of sourceFile.statements) {
    if (ts.isInterfaceDeclaration(statement) || ts.isTypeAliasDeclaration(statement)) {
      map.set(statement.name.text, statement);
    }
  }
  return map;
}

function propMembersToList(members, sourceFile) {
  return members
    .filter((member) => ts.isPropertySignature(member) && member.name)
    .map((member) => ({
      name: member.name.getText(sourceFile).replace(/^['"]|['"]$/g, ""),
      type: member.type?.getText(sourceFile) ?? "unknown",
      required: !member.questionToken,
    }));
}

function resolveProps(typeNode, localTypes, sourceFile, seen = new Set()) {
  if (!typeNode) return [];
  if (ts.isTypeLiteralNode(typeNode)) return propMembersToList(typeNode.members, sourceFile);
  if (ts.isIntersectionTypeNode(typeNode)) {
    return typeNode.types.flatMap((part) => resolveProps(part, localTypes, sourceFile, seen));
  }
  if (ts.isTypeReferenceNode(typeNode) && ts.isIdentifier(typeNode.typeName)) {
    const name = typeNode.typeName.text;
    if (seen.has(name)) return [];
    seen.add(name);
    const declaration = localTypes.get(name);
    if (!declaration) return [];
    if (ts.isInterfaceDeclaration(declaration)) {
      return propMembersToList(declaration.members, sourceFile);
    }
    if (ts.isTypeAliasDeclaration(declaration)) {
      return resolveProps(declaration.type, localTypes, sourceFile, seen);
    }
  }
  return [];
}

function humanize(value) {
  return value
    .replace(/\.[^.]+$/, "")
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .replace(/[-_]+/g, " ")
    .replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function classify(filePath) {
  const p = posix(relative(uiRoot, filePath));
  if (p.includes("/charts/")) return "chart";
  if (p.includes("/buttons/")) return "button";
  if (p.includes("/inputs/")) return "input";
  if (p.includes("/tables/") || p.includes("/data-grid/")) return "table";
  if (p.includes("/metrics-core/")) return "metric";
  if (p.includes("/metrics-layouts/") || p.includes("/layouts/")) return "layout";
  return "generic";
}

function storyTitle(filePath, exportName) {
  const rel = posix(relative(uiRoot, filePath));
  const parts = rel.split("/");
  parts.pop();
  return [...parts.map(humanize), humanize(exportName)].join("/");
}

function inferArgs(component) {
  const props = new Map(component.props.map((prop) => [prop.name, prop]));
  const args = [];

  if (component.family === "chart") {
    if (props.has("data")) args.push(`data: [\n      { month: "Jan", revenue: 120, budget: 110 },\n      { month: "Feb", revenue: 145, budget: 125 },\n      { month: "Mar", revenue: 138, budget: 132 },\n    ]`);
    if (props.has("index")) args.push(`index: "month"`);
    if (props.has("categories")) args.push(`categories: ["revenue", "budget"]`);
  }

  if (component.family === "metric") {
    if (props.has("title")) args.push(`title: "Revenue"`);
    if (props.has("label")) args.push(`label: "Revenue"`);
    if (props.has("value")) args.push(`value: "$164K"`);
    if (props.has("description")) args.push(`description: "Current period performance"`);
  }

  for (const prop of component.props) {
    if (args.some((entry) => entry.startsWith(`${prop.name}:`))) continue;
    if (prop.name === "children") args.push(`children: "${humanize(component.exportName)}"`);
    else if (prop.required && /(^|\W)string(\W|$)/.test(prop.type)) args.push(`${prop.name}: "${humanize(prop.name)}"`);
    else if (prop.required && prop.type.trim() === "number") args.push(`${prop.name}: 1`);
    else if (prop.required && prop.type.trim() === "boolean") args.push(`${prop.name}: false`);
    else if (prop.required && /=>/.test(prop.type)) args.push(`${prop.name}: () => {}`);
  }

  const resolved = new Set(args.map((entry) => entry.split(":")[0].trim()));
  const unresolved = component.props.filter((prop) => prop.required && !resolved.has(prop.name));
  return { args, unresolved };
}

function renderArgs(args) {
  if (args.length === 0) return "{}";
  return `{\n${args.map((arg) => arg.split("\n").map((line) => `    ${line}`).join("\n")).join(",\n")},\n  }`;
}

function renderStory(component, sourceHash) {
  const inferred = inferArgs(component);
  const todo = inferred.unresolved.length
    ? `\n// TODO(story): Provide representative values for required props:\n${inferred.unresolved.map((prop) => `// - ${prop.name}: ${prop.type}`).join("\n")}\n`
    : "\n";

  return `${GENERATED}\n${HASH_PREFIX}${sourceHash}\n${todo}import type { Meta, StoryObj } from "@storybook/react";\n\nimport { ${component.exportName} } from "./${component.basename}";\n\nconst meta = {\n  title: "${component.title}",\n  component: ${component.exportName},\n  tags: ["autodocs"],\n  parameters: {\n    layout: "padded",\n  },\n  args: ${renderArgs(inferred.args)},\n} satisfies Meta<typeof ${component.exportName}>;\n\nexport default meta;\n\ntype Story = StoryObj<typeof meta>;\n\nexport const Default: Story = {};\n`;
}

async function inspect(filePath) {
  const sourceText = await readFile(filePath, "utf8");
  const sourceFile = ts.createSourceFile(filePath, sourceText, ts.ScriptTarget.Latest, true, ts.ScriptKind.TSX);
  const { declarations, exported } = collectDeclarations(sourceFile);
  const localTypes = collectLocalTypes(sourceFile);
  const components = [];

  for (const exportName of exported) {
    const declaration = declarations.get(exportName);
    if (!componentName(exportName) || !isComponentDeclaration(declaration)) continue;
    components.push({
      exportName,
      sourcePath: filePath,
      sourceText,
      storyPath: filePath.replace(/\.(tsx|jsx)$/, ".stories.tsx"),
      sourceRelative: posix(relative(repoRoot, filePath)),
      storyRelative: posix(relative(repoRoot, filePath.replace(/\.(tsx|jsx)$/, ".stories.tsx"))),
      basename: filePath.split(sep).pop().replace(/\.(tsx|jsx)$/, ""),
      props: resolveProps(propsTypeNode(declaration), localTypes, sourceFile),
      family: classify(filePath),
      title: storyTitle(filePath, exportName),
    });
  }

  return components;
}

async function main() {
  const options = parseArgs(process.argv.slice(2));
  const roots = options.folder ? [resolve(repoRoot, options.folder)] : defaultRoots;
  const files = (await Promise.all(roots.map(walk))).flat();
  const components = (await Promise.all(files.map(inspect))).flat().filter((component) => {
    if (!options.component) return true;
    const needle = options.component.toLowerCase();
    return component.exportName.toLowerCase().includes(needle) || component.sourceRelative.toLowerCase().includes(needle);
  });

  const report = {
    generatedAt: new Date().toISOString(),
    mode: options.check ? "check" : options.dryRun ? "dry-run" : "write",
    totals: { components: components.length, created: 0, skipped: 0, missing: 0 },
    items: [],
  };

  for (const component of components) {
    const exists = existsSync(component.storyPath);
    if (exists && !options.force) {
      report.totals.skipped += 1;
      report.items.push({ component: component.exportName, story: component.storyRelative, status: "skipped-existing" });
      continue;
    }

    if (options.check) {
      if (!exists) {
        report.totals.missing += 1;
        report.items.push({ component: component.exportName, story: component.storyRelative, status: "missing" });
      }
      continue;
    }

    if (!options.dryRun) {
      await mkdir(dirname(component.storyPath), { recursive: true });
      await writeFile(component.storyPath, renderStory(component, hash(component.sourceText)), "utf8");
    }

    report.totals.created += 1;
    report.items.push({ component: component.exportName, story: component.storyRelative, status: options.dryRun ? "would-create" : "created" });
  }

  const reportPath = resolve(repoRoot, options.report);
  await mkdir(dirname(reportPath), { recursive: true });
  await writeFile(reportPath, `${JSON.stringify(report, null, 2)}\n`, "utf8");

  console.log(`Components: ${report.totals.components}`);
  console.log(`Created: ${report.totals.created}`);
  console.log(`Skipped: ${report.totals.skipped}`);
  console.log(`Missing: ${report.totals.missing}`);
  console.log(`Report: ${posix(relative(repoRoot, reportPath))}`);

  if (options.check && report.totals.missing > 0) process.exitCode = 1;
}

main().catch((error) => {
  console.error(error instanceof Error ? error.stack ?? error.message : error);
  process.exitCode = 1;
});
