// @generated by Metrics Storybook story generator
// @source-hash: f9aac41a3d9770d7

import type { Meta, StoryObj } from "@storybook/react";

import { Particle } from "./combobox-option";

const meta = {
  title: "Primitives/Inputs/Particle",
  component: Particle,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof Particle>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
