// @generated by Metrics Storybook story generator
// @source-hash: 73aad8693457d743

import type { Meta, StoryObj } from "@storybook/react";

import { InputGroupBlockStart } from "./input-group-block-start";

const meta = {
  title: "Primitives/Inputs/Input Group Block Start",
  component: InputGroupBlockStart,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputGroupBlockStart>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
