// @generated by Metrics Storybook story generator
// @source-hash: 32222a14fb8efa39

import type { Meta, StoryObj } from "@storybook/react";

import { InputGroupTextareaExamples } from "./input-group-textarea-examples";

const meta = {
  title: "Primitives/Inputs/Input Group Textarea Examples",
  component: InputGroupTextareaExamples,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputGroupTextareaExamples>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
