// @generated by Metrics Storybook story generator
// @source-hash: 95bdb1896c6e410b

import type { Meta, StoryObj } from "@storybook/react-vite";

import { InputOTPWithSeparator } from "./input-otp-separator";

const meta = {
  title: "Primitives/Inputs/Input OTPWith Separator",
  component: InputOTPWithSeparator,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputOTPWithSeparator>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
