// @generated by Metrics Storybook story generator
// @source-hash: 93461911853314ac

import type { Meta, StoryObj } from "@storybook/react";

import { InputFieldgroup } from "./input-fieldgroup";

const meta = {
  title: "Primitives/Inputs/Input Fieldgroup",
  component: InputFieldgroup,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputFieldgroup>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
