// @generated by Metrics Storybook story generator
// @source-hash: 074491f7de7e1053

import type { Meta, StoryObj } from "@storybook/react-vite";

import { InputGroupCustom } from "./input-group-custom";

const meta = {
  title: "Primitives/Inputs/Input Group Custom",
  component: InputGroupCustom,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputGroupCustom>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
