// @generated by Metrics Storybook story generator
// @source-hash: 6c59292e079bf589

import type { Meta, StoryObj } from "@storybook/react-vite";

import { InputGroupBlockEnd } from "./input-group-block-end";

const meta = {
  title: "Primitives/Inputs/Input Group Block End",
  component: InputGroupBlockEnd,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputGroupBlockEnd>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
