// @generated by Metrics Storybook story generator
// @source-hash: 0a658e53779ec370

import type { Meta, StoryObj } from "@storybook/react-vite";

import { InputOTPDisabled } from "./input-otp-disabled";

const meta = {
  title: "Primitives/Inputs/Input OTPDisabled",
  component: InputOTPDisabled,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputOTPDisabled>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
