// @generated by Metrics Storybook story generator
// @source-hash: 27d2895c87a0d07b

import type { Meta, StoryObj } from "@storybook/react-vite";

import { InputGroupWithKbd } from "./input-group-with-kbd";

const meta = {
  title: "Primitives/Inputs/Input Group With Kbd",
  component: InputGroupWithKbd,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputGroupWithKbd>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
