// @generated by Metrics Storybook story generator
// @source-hash: c695406ae633cbb0

import type { Meta, StoryObj } from "@storybook/react-vite";

import { InputGroupSpinner } from "./input-group-spinner";

const meta = {
  title: "Primitives/Inputs/Input Group Spinner",
  component: InputGroupSpinner,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputGroupSpinner>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
