// @generated by Metrics Storybook story generator
// @source-hash: 6c29c3937c4191db

import type { Meta, StoryObj } from "@storybook/react-vite";

import { InputGroupInlineStart } from "./input-group-inline-start";

const meta = {
  title: "Primitives/Inputs/Input Group Inline Start",
  component: InputGroupInlineStart,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputGroupInlineStart>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
