// @generated by Metrics Storybook story generator
// @source-hash: f0994302358224ec

import type { Meta, StoryObj } from "@storybook/react";

import { InputGroupInlineEnd } from "./input-group-inline-end";

const meta = {
  title: "Primitives/Inputs/Input Group Inline End",
  component: InputGroupInlineEnd,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputGroupInlineEnd>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
