// @generated by Metrics Storybook story generator
// @source-hash: 4eb9df083b02feaf

import type { Meta, StoryObj } from "@storybook/react-vite";

import { InputOTPInvalid } from "./input-otp-invalid";

const meta = {
  title: "Primitives/Inputs/Input OTPInvalid",
  component: InputOTPInvalid,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputOTPInvalid>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
