// @generated by Metrics Storybook story generator
// @source-hash: fbda776e2ba9dcb4

import type { Meta, StoryObj } from "@storybook/react";

import { InputInline } from "./input-inline";

const meta = {
  title: "Primitives/Inputs/Input Inline",
  component: InputInline,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputInline>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
