// @generated by Metrics Storybook story generator
// @source-hash: 4802a6a39ce8a3a1

import type { Meta, StoryObj } from "@storybook/react-vite";

import { InputButtonGroup } from "./input-button-group";

const meta = {
  title: "Primitives/Inputs/Input Button Group",
  component: InputButtonGroup,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputButtonGroup>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
