// @generated by Metrics Storybook story generator
// @source-hash: 5c974b817eedb7f7

import type { Meta, StoryObj } from "@storybook/react-vite";

import { InputGroupButtonExample } from "./input-group-button";

const meta = {
  title: "Primitives/Inputs/Input Group Button Example",
  component: InputGroupButtonExample,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputGroupButtonExample>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
