// @generated by Metrics Storybook story generator
// @source-hash: 5b564281a425775d

import type { Meta, StoryObj } from "@storybook/react-vite";

import { InputForm } from "./input-form";

const meta = {
  title: "Primitives/Inputs/Input Form",
  component: InputForm,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputForm>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
