// @generated by Metrics Storybook story generator
// @source-hash: 170958715032b668

import type { Meta, StoryObj } from "@storybook/react-vite";

import { InputGroupWithTooltip } from "./input-group-with-tooltip";

const meta = {
  title: "Primitives/Inputs/Input Group With Tooltip",
  component: InputGroupWithTooltip,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputGroupWithTooltip>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
