// @generated by Metrics Storybook story generator
// @source-hash: e84ff6b830bb79a2

import type { Meta, StoryObj } from "@storybook/react";

import { InputOTPAlphanumeric } from "./input-otp-alphanumeric";

const meta = {
  title: "Primitives/Inputs/Input OTPAlphanumeric",
  component: InputOTPAlphanumeric,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputOTPAlphanumeric>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
