// @generated by Metrics Storybook story generator
// @source-hash: e886efa70fd1b309

import type { Meta, StoryObj } from "@storybook/react";

import { InputGroupWithButtons } from "./input-group-with-buttons";

const meta = {
  title: "Primitives/Inputs/Input Group With Buttons",
  component: InputGroupWithButtons,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputGroupWithButtons>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
