// @generated by Metrics Storybook story generator
// @source-hash: fe3aa5b11f0a53ce

import type { Meta, StoryObj } from "@storybook/react";

import { InputGroup } from "./input-group";

const meta = {
  title: "Primitives/Inputs/Input Group",
  component: InputGroup,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputGroup>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
