// @generated by Metrics Storybook story generator
// @source-hash: 7979de5aaf089a69

import type { Meta, StoryObj } from "@storybook/react";

import { InputInvalid } from "./input-invalid";

const meta = {
  title: "Primitives/Inputs/Input Invalid",
  component: InputInvalid,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputInvalid>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
