// @generated by Metrics Storybook story generator
// @source-hash: 8e457377f2ad41a5

import type { Meta, StoryObj } from "@storybook/react-vite";

import { InputDisabled } from "./input-disabled";

const meta = {
  title: "Primitives/Inputs/Input Disabled",
  component: InputDisabled,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputDisabled>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
