// @generated by Metrics Storybook story generator
// @source-hash: acb043722952757a

import type { Meta, StoryObj } from "@storybook/react";

import { InputOTP } from "./input-otp";

const meta = {
  title: "Primitives/Inputs/Input OTP",
  component: InputOTP,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputOTP>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
