// @generated by Metrics Storybook story generator
// @source-hash: c166b22bf0b2c3da

import type { Meta, StoryObj } from "@storybook/react-vite";

import { InputGroupTextExample } from "./input-group-text";

const meta = {
  title: "Primitives/Inputs/Input Group Text Example",
  component: InputGroupTextExample,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputGroupTextExample>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
