// @generated by Metrics Storybook story generator
// @source-hash: 74f352ae1efdfd4f

import type { Meta, StoryObj } from "@storybook/react-vite";

import { InputOTPControlled } from "./input-otp-controlled";

const meta = {
  title: "Primitives/Inputs/Input OTPControlled",
  component: InputOTPControlled,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputOTPControlled>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
