// @generated by Metrics Storybook story generator
// @source-hash: e7ce9bc44c56798c

import type { Meta, StoryObj } from "@storybook/react-vite";

import { InputOTPForm } from "./input-otp-form";

const meta = {
  title: "Primitives/Inputs/Input OTPForm",
  component: InputOTPForm,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputOTPForm>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
