// @generated by Metrics Storybook story generator
// @source-hash: 86d16059d119e41d

import type { Meta, StoryObj } from "@storybook/react-vite";

import { InputGroupLabel } from "./input-group-label";

const meta = {
  title: "Primitives/Inputs/Input Group Label",
  component: InputGroupLabel,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputGroupLabel>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
