// @generated by Metrics Storybook story generator
// @source-hash: a428a57fe81ed65a

import type { Meta, StoryObj } from "@storybook/react";

import { InputGrid } from "./input-grid";

const meta = {
  title: "Primitives/Inputs/Input Grid",
  component: InputGrid,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputGrid>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
