// @generated by Metrics Storybook story generator
// @source-hash: f0bcdbcf7b47bff7

import type { Meta, StoryObj } from "@storybook/react-vite";

import { InputGroupButtonGroup } from "./input-group-button-group";

const meta = {
  title: "Primitives/Inputs/Input Group Button Group",
  component: InputGroupButtonGroup,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputGroupButtonGroup>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
