// @generated by Metrics Storybook story generator
// @source-hash: 838e1338de4df7e4

import type { Meta, StoryObj } from "@storybook/react";

import { InputField } from "./input-field";

const meta = {
  title: "Primitives/Inputs/Input Field",
  component: InputField,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputField>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
