// @generated by Metrics Storybook story generator
// @source-hash: a29884c2c569918e

import type { Meta, StoryObj } from "@storybook/react-vite";

import { InputFile } from "./input-file";

const meta = {
  title: "Primitives/Inputs/Input File",
  component: InputFile,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputFile>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
