// @generated by Metrics Storybook story generator
// @source-hash: 523671b8fcded9dc

import type { Meta, StoryObj } from "@storybook/react-vite";

import { InputGroupIcon } from "./input-group-icon";

const meta = {
  title: "Primitives/Inputs/Input Group Icon",
  component: InputGroupIcon,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputGroupIcon>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
