// @generated by Metrics Storybook story generator
// @source-hash: 8f38b965fcd641e1

import type { Meta, StoryObj } from "@storybook/react-vite";

import { InputGroupTooltip } from "./input-group-tooltip";

const meta = {
  title: "Primitives/Inputs/Input Group Tooltip",
  component: InputGroupTooltip,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputGroupTooltip>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
