// @generated by Metrics Storybook story generator
// @source-hash: c4592ad786087d89

import type { Meta, StoryObj } from "@storybook/react-vite";

import { InputInputGroup } from "./input-input-group";

const meta = {
  title: "Primitives/Inputs/Input Input Group",
  component: InputInputGroup,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputInputGroup>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
