// @generated by Metrics Storybook story generator
// @source-hash: 048495964dfa0c41

import type { Meta, StoryObj } from "@storybook/react-vite";

import { InputBadge } from "./input-badge";

const meta = {
  title: "Primitives/Inputs/Input Badge",
  component: InputBadge,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputBadge>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
