// @generated by Metrics Storybook story generator
// @source-hash: 58f61e69019dc9ac

import type { Meta, StoryObj } from "@storybook/react";

import { InputGroupInCard } from "./input-group-in-card";

const meta = {
  title: "Primitives/Inputs/Input Group In Card",
  component: InputGroupInCard,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputGroupInCard>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
