// @generated by Metrics Storybook story generator
// @source-hash: 92cd7eab02e477a9

import type { Meta, StoryObj } from "@storybook/react-vite";

import { InputGroupKbd } from "./input-group-kbd";

const meta = {
  title: "Primitives/Inputs/Input Group Kbd",
  component: InputGroupKbd,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputGroupKbd>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
