// @generated by Metrics Storybook story generator
// @source-hash: 832ff33183ab8b1b

import type { Meta, StoryObj } from "@storybook/react-vite";

import { InputGroupDropdown } from "./input-group-dropdown";

const meta = {
  title: "Primitives/Inputs/Input Group Dropdown",
  component: InputGroupDropdown,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputGroupDropdown>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
