// @generated by Metrics Storybook story generator
// @source-hash: b67e4c6227cd3ffa

import type { Meta, StoryObj } from "@storybook/react-vite";

import { InputOTPPattern } from "./input-otp-pattern";

const meta = {
  title: "Primitives/Inputs/Input OTPPattern",
  component: InputOTPPattern,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputOTPPattern>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
