// @generated by Metrics Storybook story generator
// @source-hash: b29a1433184f510e

import type { Meta, StoryObj } from "@storybook/react-vite";

import { InputGroupTextareaExample } from "./input-group-textarea";

const meta = {
  title: "Primitives/Inputs/Input Group Textarea Example",
  component: InputGroupTextareaExample,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputGroupTextareaExample>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
