// @generated by Metrics Storybook story generator
// @source-hash: 1afbfeb50bb5d4df

import type { Meta, StoryObj } from "@storybook/react";

import { InputGroupWithAddons } from "./input-group-with-addons";

const meta = {
  title: "Primitives/Inputs/Input Group With Addons",
  component: InputGroupWithAddons,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputGroupWithAddons>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
