// @generated by Metrics Storybook story generator
// @source-hash: 2141acd15e300082

import type { Meta, StoryObj } from "@storybook/react-vite";

import { InputBasic } from "./input-basic";

const meta = {
  title: "Primitives/Inputs/Input Basic",
  component: InputBasic,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputBasic>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
