// @generated by Metrics Storybook story generator
// @source-hash: 9bed07805a33c413

import type { Meta, StoryObj } from "@storybook/react-vite";

import { InputOTPFourDigits } from "./input-otp-four-digits";

const meta = {
  title: "Primitives/Inputs/Input OTPFour Digits",
  component: InputOTPFourDigits,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputOTPFourDigits>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
