// @generated by Metrics Storybook story generator
// @source-hash: 690aa31dc69ab4af

import type { Meta, StoryObj } from "@storybook/react-vite";

import { InputGroupBasic } from "./input-group-basic";

const meta = {
  title: "Primitives/Inputs/Input Group Basic",
  component: InputGroupBasic,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof InputGroupBasic>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
