// @generated by Metrics Storybook story generator
// @source-hash: 4494fb9d3fc7edf0

import type { Meta, StoryObj } from "@storybook/react";

import { ButtonGhost } from "./button-ghost";

const meta = {
  title: "Primitives/Buttons/Button Ghost",
  component: ButtonGhost,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ButtonGhost>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
