// @generated by Metrics Storybook story generator
// @source-hash: 95d9830a162fe7d0

import type { Meta, StoryObj } from "@storybook/react";

import { ButtonWithIcon } from "./button-with-icon";

const meta = {
  title: "Primitives/Buttons/Button With Icon",
  component: ButtonWithIcon,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ButtonWithIcon>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
