// @generated by Metrics Storybook story generator
// @source-hash: 8d3f98b8e776abef

import type { Meta, StoryObj } from "@storybook/react";

import { ButtonGroupInputGroup } from "./button-group-input-group";

const meta = {
  title: "Primitives/Buttons/Button Group Input Group",
  component: ButtonGroupInputGroup,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ButtonGroupInputGroup>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
