// @generated by Metrics Storybook story generator
// @source-hash: 4d47d405f8a6e8b8

import type { Meta, StoryObj } from "@storybook/react-vite";

import { ButtonOutline } from "./button-outline";

const meta = {
  title: "Primitives/Buttons/Button Outline",
  component: ButtonOutline,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ButtonOutline>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
