// @generated by Metrics Storybook story generator
// @source-hash: 6b75c222f91cee2d

import type { Meta, StoryObj } from "@storybook/react";

import { ButtonGroupSeparatorDemo } from "./button-group-separator";

const meta = {
  title: "Primitives/Buttons/Button Group Separator Demo",
  component: ButtonGroupSeparatorDemo,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ButtonGroupSeparatorDemo>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
