// @generated by Metrics Storybook story generator
// @source-hash: 3982f4a267427bfc

import type { Meta, StoryObj } from "@storybook/react-vite";

import { ButtonRounded } from "./button-rounded";

const meta = {
  title: "Primitives/Buttons/Button Rounded",
  component: ButtonRounded,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ButtonRounded>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
