// @generated by Metrics Storybook story generator
// @source-hash: 25a91126edfdb9db

import type { Meta, StoryObj } from "@storybook/react-vite";

import { ButtonDestructive } from "./button-destructive";

const meta = {
  title: "Primitives/Buttons/Button Destructive",
  component: ButtonDestructive,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ButtonDestructive>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
