// @generated by Metrics Storybook story generator
// @source-hash: 7cc927c2950f5a66

import type { Meta, StoryObj } from "@storybook/react-vite";

import { ButtonGroupNested } from "./button-group-nested";

const meta = {
  title: "Primitives/Buttons/Button Group Nested",
  component: ButtonGroupNested,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ButtonGroupNested>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
