// @generated by Metrics Storybook story generator
// @source-hash: 106d4e99247a7c25

import type { Meta, StoryObj } from "@storybook/react";

import { ButtonSize } from "./button-size";

const meta = {
  title: "Primitives/Buttons/Button Size",
  component: ButtonSize,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ButtonSize>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
