// @generated by Metrics Storybook story generator
// @source-hash: 7030f05dd2da7979

import type { Meta, StoryObj } from "@storybook/react";

import { ButtonGroupSplit } from "./button-group-split";

const meta = {
  title: "Primitives/Buttons/Button Group Split",
  component: ButtonGroupSplit,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ButtonGroupSplit>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
