// @generated by Metrics Storybook story generator
// @source-hash: f3c2e3c2a7eaeca7

import type { Meta, StoryObj } from "@storybook/react-vite";

import { ButtonGroupSelect } from "./button-group-select";

const meta = {
  title: "Primitives/Buttons/Button Group Select",
  component: ButtonGroupSelect,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ButtonGroupSelect>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
