// @generated by Metrics Storybook story generator
// @source-hash: 10d103b4bff0cadf

import type { Meta, StoryObj } from "@storybook/react-vite";

import { ButtonLink } from "./button-link";

const meta = {
  title: "Primitives/Buttons/Button Link",
  component: ButtonLink,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ButtonLink>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
