// @generated by Metrics Storybook story generator
// @source-hash: 50dcbad50aaa096e

import type { Meta, StoryObj } from "@storybook/react";

import { ButtonGroupPopover } from "./button-group-popover";

const meta = {
  title: "Primitives/Buttons/Button Group Popover",
  component: ButtonGroupPopover,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ButtonGroupPopover>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
