// @generated by Metrics Storybook story generator
// @source-hash: 22490479911ec70d

import type { Meta, StoryObj } from "@storybook/react-vite";

import { ButtonGroupSize } from "./button-group-size";

const meta = {
  title: "Primitives/Buttons/Button Group Size",
  component: ButtonGroupSize,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ButtonGroupSize>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
