// @generated by Metrics Storybook story generator
// @source-hash: da11858c9223a75d

import type { Meta, StoryObj } from "@storybook/react";

import { ButtonDefault } from "./button-default";

const meta = {
  title: "Primitives/Buttons/Button Default",
  component: ButtonDefault,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ButtonDefault>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
