// @generated by Metrics Storybook story generator
// @source-hash: d618bef540122c3d

import type { Meta, StoryObj } from "@storybook/react-vite";

import { ButtonIcon } from "./button-icon";

const meta = {
  title: "Primitives/Buttons/Button Icon",
  component: ButtonIcon,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ButtonIcon>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
