// @generated by Metrics Storybook story generator
// @source-hash: 3bcefb0db9c53317

import type { Meta, StoryObj } from "@storybook/react-vite";

import { ButtonLoading } from "./button-spinner";

const meta = {
  title: "Primitives/Buttons/Button Loading",
  component: ButtonLoading,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ButtonLoading>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
