// @generated by Metrics Storybook story generator
// @source-hash: f8ed2d17c45627ca

import type { Meta, StoryObj } from "@storybook/react-vite";

import { ButtonGroup } from "./button-group";

const meta = {
  title: "Primitives/Buttons/Button Group",
  component: ButtonGroup,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ButtonGroup>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
