// @generated by Metrics Storybook story generator
// @source-hash: 83a2ddb28cf4cbce

import type { Meta, StoryObj } from "@storybook/react";

import { ButtonRender } from "./button-render";

const meta = {
  title: "Primitives/Buttons/Button Render",
  component: ButtonRender,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ButtonRender>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
