// @generated by Metrics Storybook story generator
// @source-hash: e63c135acbd24cfc

import type { Meta, StoryObj } from "@storybook/react";

import { ButtonGroupDropdown } from "./button-group-dropdown";

const meta = {
  title: "Primitives/Buttons/Button Group Dropdown",
  component: ButtonGroupDropdown,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ButtonGroupDropdown>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
