// @generated by Metrics Storybook story generator
// @source-hash: a78b7ccc962547a4

import type { Meta, StoryObj } from "@storybook/react-vite";

import { ButtonGroupOrientation } from "./button-group-orientation";

const meta = {
  title: "Primitives/Buttons/Button Group Orientation",
  component: ButtonGroupOrientation,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ButtonGroupOrientation>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
