// @generated by Metrics Storybook story generator
// @source-hash: 10a59f9428a1a52d

import type { Meta, StoryObj } from "@storybook/react-vite";

import { DiscoverButton } from "./discover-button";

const meta = {
  title: "Primitives/Buttons/Discover Button",
  component: DiscoverButton,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof DiscoverButton>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
