// @generated by Metrics Storybook story generator
// @source-hash: 34fd533f22fa45de

import type { Meta, StoryObj } from "@storybook/react-vite";

import { SaveButton } from "./status-button";

const meta = {
  title: "Primitives/Buttons/Save Button",
  component: SaveButton,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof SaveButton>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
