// @generated by Metrics Storybook story generator
// @source-hash: 748dfa15b4ccc974

import type { Meta, StoryObj } from "@storybook/react";

import { ToolbarButton } from "./toolbar-button";

const meta = {
  title: "Primitives/Buttons/Toolbar Button",
  component: ToolbarButton,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ToolbarButton>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
