// @generated by Metrics Storybook story generator
// @source-hash: 5170e840be6f9a1e

import type { Meta, StoryObj } from "@storybook/react";

import { DiscreteTabs } from "./discrete-tabs";

const meta = {
  title: "Primitives/Tabs/Discrete Tabs",
  component: DiscreteTabs,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof DiscreteTabs>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
