// @generated by Metrics Storybook story generator
// @source-hash: daf00866c9ac8660

import type { Meta, StoryObj } from "@storybook/react-vite";

import { TabsLine } from "./tabs-line";

const meta = {
  title: "Primitives/Tabs/Tabs Line",
  component: TabsLine,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof TabsLine>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
