// @generated by Metrics Storybook story generator
// @source-hash: fa61a4848cc54130

import type { Meta, StoryObj } from "@storybook/react";

import { TabsIcons } from "./tabs-icons";

const meta = {
  title: "Primitives/Tabs/Tabs Icons",
  component: TabsIcons,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof TabsIcons>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
