// @generated by Metrics Storybook story generator
// @source-hash: 53e429a585316c2d

import type { Meta, StoryObj } from "@storybook/react";

import { TabsDisabled } from "./tabs-disabled";

const meta = {
  title: "Primitives/Tabs/Tabs Disabled",
  component: TabsDisabled,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof TabsDisabled>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
