// @generated by Metrics Storybook story generator
// @source-hash: aa74c90bad45bada

import type { Meta, StoryObj } from "@storybook/react-vite";

import { TabsVertical } from "./tabs-vertical";

const meta = {
  title: "Primitives/Tabs/Tabs Vertical",
  component: TabsVertical,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof TabsVertical>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
