// @generated by Metrics Storybook story generator
// @source-hash: 784c5153e2e89afd

import type { Meta, StoryObj } from "@storybook/react";

import { Tabs } from "./tabs";

const meta = {
  title: "Primitives/Tabs/Tabs",
  component: Tabs,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof Tabs>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
