// @generated by Metrics Storybook story generator
// @source-hash: fb203f2e275a9767

import type { Meta, StoryObj } from "@storybook/react-vite";

import { TableFooterExample } from "./table-footer";

const meta = {
  title: "Primitives/Tables/Table Footer Example",
  component: TableFooterExample,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof TableFooterExample>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
