// @generated by Metrics Storybook story generator
// @source-hash: c191f7c37624332e

import type { Meta, StoryObj } from "@storybook/react";

import { TableActions } from "./table-actions";

const meta = {
  title: "Primitives/Tables/Table Actions",
  component: TableActions,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof TableActions>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
