// @generated by Metrics Storybook story generator
// @source-hash: f4f524e4ed837920

import type { Meta, StoryObj } from "@storybook/react";

import { Table } from "./table";

const meta = {
  title: "Primitives/Tables/Table",
  component: Table,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof Table>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
