// @generated by Metrics Storybook story generator
// @source-hash: b4981c8bbc46a247

import type { Meta, StoryObj } from "@storybook/react";

import { ContactRevrebelPage } from "./helpdesk_page";

const meta = {
  title: "Components/Metrics Layouts/Help Desk/Contact Revrebel Page",
  component: ContactRevrebelPage,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ContactRevrebelPage>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
