// @generated by Metrics Storybook story generator
// @source-hash: 38f3e243dc3ac281

import type { Meta, StoryObj } from "@storybook/react";

import { HelpDeskPage } from "./helpdesk_layout";

const meta = {
  title: "Components/Metrics Layouts/Help Desk/Help Desk Page",
  component: HelpDeskPage,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof HelpDeskPage>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
