// @generated by Metrics Storybook story generator
// @source-hash: e17d6c941e6d04a3

// TODO(story): Provide representative values for required props:
// - editor: Editor
import type { Meta, StoryObj } from "@storybook/react";

import { LinkEditPopover } from "./link-edit-popover";

const meta = {
  title: "Primitives/Links/Link Edit Popover",
  component: LinkEditPopover,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof LinkEditPopover>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
