// @generated by Metrics Storybook story generator
// @source-hash: 4dda8287617de7d9

import type { Meta, StoryObj } from "@storybook/react";

import { LinkBubbleMenu } from "./link-bubble-menu";

const meta = {
  title: "Primitives/Links/Link Bubble Menu",
  component: LinkBubbleMenu,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof LinkBubbleMenu>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
