// @generated by Metrics Storybook story generator
// @source-hash: 2f726c532558d872

import type { Meta, StoryObj } from "@storybook/react";

import { LinkEditBlock } from "./link-edit-block";

const meta = {
  title: "Primitives/Links/Link Edit Block",
  component: LinkEditBlock,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {
    onSave: "On Save",
  },
} satisfies Meta<typeof LinkEditBlock>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
