// @generated by Metrics Storybook story generator
// @source-hash: c93545e04c3d7b86

import type { Meta, StoryObj } from "@storybook/react-vite";

import { LinkPopoverBlock } from "./link-popover-block";

const meta = {
  title: "Primitives/Links/Link Popover Block",
  component: LinkPopoverBlock,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof LinkPopoverBlock>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
