// @generated by Metrics Storybook story generator
// @source-hash: 4583a08af8da355b

// TODO(story): Provide representative values for required props:
// - tasks: Task[]
import type { Meta, StoryObj } from "@storybook/react-vite";

import { CalendarView } from "./calendar-view_page";

const meta = {
  title: "Components/Metrics Layouts/Tasks/Calendar View",
  component: CalendarView,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof CalendarView>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
