// @generated by Metrics Storybook story generator
// @source-hash: f23744a0d9463a72

// TODO(story): Provide representative values for required props:
// - row: Row<TData>
import type { Meta, StoryObj } from "@storybook/react";

import { DataTableRowActions } from "./data-actions_table-row";

const meta = {
  title: "Components/Metrics Layouts/Tasks/Data Table Row Actions",
  component: DataTableRowActions,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof DataTableRowActions>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
