// @generated by Metrics Storybook story generator
// @source-hash: a2c7d656f8fd8b1e

// TODO(story): Provide representative values for required props:
// - table: Table<TData>
import type { Meta, StoryObj } from "@storybook/react";

import { DataTableBulkActions } from "./data-bulk-actions_table";

const meta = {
  title: "Components/Metrics Layouts/Tasks/Data Table Bulk Actions",
  component: DataTableBulkActions,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof DataTableBulkActions>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
