// @generated by Metrics Storybook story generator
// @source-hash: 516a419eec609143

// TODO(story): Provide representative values for required props:
// - tasks: Task[]
import type { Meta, StoryObj } from "@storybook/react";

import { ByPersonView } from "./group-views";

const meta = {
  title: "Components/Metrics Layouts/Tasks/By Person View",
  component: ByPersonView,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ByPersonView>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
