// @generated by Metrics Storybook story generator
// @source-hash: 021ba464745f5a59

// TODO(story): Provide representative values for required props:
// - view: GrowthPlanView
// - mode: "initiatives" | "tasks"
import type { Meta, StoryObj } from "@storybook/react";

import { EmptyState } from "./growth-plan_states";

const meta = {
  title: "Components/Metrics Layouts/Tasks/Empty State",
  component: EmptyState,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof EmptyState>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
