// @generated by Metrics Storybook story generator
// @source-hash: 1d0688f911d67e64

// TODO(story): Provide representative values for required props:
// - mode: GrowthPlanMode
import type { Meta, StoryObj } from "@storybook/react";

import { GrowthPlanHeader } from "./growth-plan_header";

const meta = {
  title: "Components/Metrics Layouts/Tasks/Growth Plan Header",
  component: GrowthPlanHeader,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {
    onModeChange: () => {},
  },
} satisfies Meta<typeof GrowthPlanHeader>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
