// @generated by Metrics Storybook story generator
// @source-hash: 5f71165aaead9817

// TODO(story): Provide representative values for required props:
// - initiatives: Initiative[]
import type { Meta, StoryObj } from "@storybook/react-vite";

import { GrowthPlanSidebar } from "./growth-plan_sidebar";

const meta = {
  title: "Components/Metrics Layouts/Tasks/Growth Plan Sidebar",
  component: GrowthPlanSidebar,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {
    onInitiativeSelect: () => {},
  },
} satisfies Meta<typeof GrowthPlanSidebar>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
