// @generated by Metrics Storybook story generator
// @source-hash: dda6ca93b9659464

// TODO(story): Provide representative values for required props:
// - initiatives: Initiative[]
// - tasks: Task[]
// - mode: "initiatives" | "tasks"
import type { Meta, StoryObj } from "@storybook/react";

import { KanbanView } from "./kanban_page";

const meta = {
  title: "Components/Metrics Layouts/Tasks/Kanban View",
  component: KanbanView,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof KanbanView>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
