// @generated by Metrics Storybook story generator
// @source-hash: c6f3212fda67a247

// TODO(story): Provide representative values for required props:
// - initiatives: Initiative[]
// - tasks: Task[]
import type { Meta, StoryObj } from "@storybook/react";

import { MeetingRecapView } from "./meeting-recap_page";

const meta = {
  title: "Components/Metrics Layouts/Tasks/Meeting Recap View",
  component: MeetingRecapView,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof MeetingRecapView>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
