// @generated by Metrics Storybook story generator
// @source-hash: 66262e03b28060f3

// TODO(story): Provide representative values for required props:
// - initiatives: Initiative[]
import type { Meta, StoryObj } from "@storybook/react-vite";

import { OwnerRollupView } from "./owner-rollup_page";

const meta = {
  title: "Components/Metrics Layouts/Tasks/Owner Rollup View",
  component: OwnerRollupView,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof OwnerRollupView>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
