// @generated by Metrics Storybook story generator
// @source-hash: 70ea127c9f4edea9

import type { Meta, StoryObj } from "@storybook/react";

import { TasksImportDialog } from "./tasks-import_dialog";

const meta = {
  title: "Components/Metrics Layouts/Tasks/Tasks Import Dialog",
  component: TasksImportDialog,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {
    open: false,
    onOpenChange: () => {},
  },
} satisfies Meta<typeof TasksImportDialog>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
