// @generated by Metrics Storybook story generator
// @source-hash: 27e00507994973bf

import type { Meta, StoryObj } from "@storybook/react-vite";

import { TasksPrimaryButtons } from "./tasks-primary-buttons";

const meta = {
  title: "Components/Metrics Layouts/Tasks/Tasks Primary Buttons",
  component: TasksPrimaryButtons,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof TasksPrimaryButtons>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
