// @generated by Metrics Storybook story generator
// @source-hash: 296d480849de6ef1

import type { Meta, StoryObj } from "@storybook/react-vite";

import { TasksDialogs } from "./tasks_dialogs";

const meta = {
  title: "Components/Metrics Layouts/Tasks/Tasks Dialogs",
  component: TasksDialogs,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof TasksDialogs>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
