// @generated by Metrics Storybook story generator
// @source-hash: b5f5924ddeec6ed0

import type { Meta, StoryObj } from "@storybook/react-vite";

import { TasksProvider } from "./tasks_provider";

const meta = {
  title: "Components/Metrics Layouts/Tasks/Tasks Provider",
  component: TasksProvider,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {
    children: "Tasks Provider",
  },
} satisfies Meta<typeof TasksProvider>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
