// @generated by Metrics Storybook story generator
// @source-hash: fef28794a6e0929d

import type { Meta, StoryObj } from "@storybook/react-vite";

import { GrowthPlanPage } from "./tasks_layout";

const meta = {
  title: "Components/Metrics Layouts/Tasks/Growth Plan Page",
  component: GrowthPlanPage,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof GrowthPlanPage>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
