// @generated by Metrics Storybook story generator
// @source-hash: eabe97a1379459e7

// TODO(story): Provide representative values for required props:
// - data: Task[]
import type { Meta, StoryObj } from "@storybook/react-vite";

import { TasksTable } from "./tasks_table";

const meta = {
  title: "Components/Metrics Layouts/Tasks/Tasks Table",
  component: TasksTable,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof TasksTable>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
