// @generated by Metrics Storybook story generator
// @source-hash: d466faf68668f129

// TODO(story): Provide representative values for required props:
// - table: Table<TData>
import type { Meta, StoryObj } from "@storybook/react-vite";

import { TasksMultiDeleteDialog } from "./tasks-multi-delete_dialog";

const meta = {
  title: "Components/Metrics Layouts/Tasks/Tasks Multi Delete Dialog",
  component: TasksMultiDeleteDialog,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {
    open: false,
    onOpenChange: () => {},
  },
} satisfies Meta<typeof TasksMultiDeleteDialog>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
