// @generated by Metrics Storybook story generator
// @source-hash: 6d0aa66b7f739c27

import type { Meta, StoryObj } from "@storybook/react-vite";

import { WorkstreamMutateDrawer } from "./workstream-mutate_drawer";

const meta = {
  title: "Components/Metrics Layouts/Tasks/Workstream Mutate Drawer",
  component: WorkstreamMutateDrawer,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {
    open: false,
    onOpenChange: () => {},
  },
} satisfies Meta<typeof WorkstreamMutateDrawer>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
