// @generated by Metrics Storybook story generator
// @source-hash: c076a09afd6abdb5

import type { Meta, StoryObj } from "@storybook/react";

import { WorkstreamsSection } from "./workstreams_section";

const meta = {
  title: "Components/Metrics Layouts/Tasks/Workstreams Section",
  component: WorkstreamsSection,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof WorkstreamsSection>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
