// @generated by Metrics Storybook story generator
// @source-hash: 7d670c2f255b5a0e

import type { Meta, StoryObj } from "@storybook/react";

import { LongText } from "./long-text";

const meta = {
  title: "Primitives/Textarea/Long Text",
  component: LongText,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {
    children: "Long Text",
  },
} satisfies Meta<typeof LongText>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
