// @generated by Metrics Storybook story generator
// @source-hash: 63a9059779e07750

import type { Meta, StoryObj } from "@storybook/react-vite";

import { TextareaDisabled } from "./textarea-disabled";

const meta = {
  title: "Primitives/Textarea/Textarea Disabled",
  component: TextareaDisabled,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof TextareaDisabled>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
