// @generated by Metrics Storybook story generator
// @source-hash: 7af437161c3cc3f3

import type { Meta, StoryObj } from "@storybook/react";

import { TextareaButton } from "./textarea-button";

const meta = {
  title: "Primitives/Textarea/Textarea Button",
  component: TextareaButton,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof TextareaButton>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
