// @generated by Metrics Storybook story generator
// @source-hash: 0213e10b4911cc4f

import type { Meta, StoryObj } from "@storybook/react";

import { TextareaField } from "./textarea-field";

const meta = {
  title: "Primitives/Textarea/Textarea Field",
  component: TextareaField,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof TextareaField>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
