// @generated by Metrics Storybook story generator
// @source-hash: 49c187a3dbfb4265

import type { Meta, StoryObj } from "@storybook/react-vite";

import { TextareaInvalid } from "./textarea-invalid";

const meta = {
  title: "Primitives/Textarea/Textarea Invalid",
  component: TextareaInvalid,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof TextareaInvalid>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
