// @generated by Metrics Storybook story generator
// @source-hash: fa2b85e3e606af22

import type { Meta, StoryObj } from "@storybook/react-vite";

import { DropdownMenuSubmenu } from "./dropdown-menu-submenu";

const meta = {
  title: "Primitives/Dropdowns/Dropdown Menu Submenu",
  component: DropdownMenuSubmenu,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof DropdownMenuSubmenu>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
