// @generated by Metrics Storybook story generator
// @source-hash: 1c055c9f7d6afeff

import type { Meta, StoryObj } from "@storybook/react";

import { DropdownMenu } from "./dropdown-menu";

const meta = {
  title: "Primitives/Dropdowns/Dropdown Menu",
  component: DropdownMenu,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof DropdownMenu>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
