// @generated by Metrics Storybook story generator
// @source-hash: 480886f066355700

import type { Meta, StoryObj } from "@storybook/react";

import { DropdownMenuRadioIcons } from "./dropdown-menu-radio-icons";

const meta = {
  title: "Primitives/Dropdowns/Dropdown Menu Radio Icons",
  component: DropdownMenuRadioIcons,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof DropdownMenuRadioIcons>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
