// @generated by Metrics Storybook story generator
// @source-hash: 9033c32ffa36b472

import type { Meta, StoryObj } from "@storybook/react";

import { DropdownMenuAvatar } from "./dropdown-menu-avatar";

const meta = {
  title: "Primitives/Dropdowns/Dropdown Menu Avatar",
  component: DropdownMenuAvatar,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof DropdownMenuAvatar>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
