// @generated by Metrics Storybook story generator
// @source-hash: cf40432e0e673fa3

import type { Meta, StoryObj } from "@storybook/react-vite";

import { DropdownMenuShortcuts } from "./dropdown-menu-shortcuts";

const meta = {
  title: "Primitives/Dropdowns/Dropdown Menu Shortcuts",
  component: DropdownMenuShortcuts,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof DropdownMenuShortcuts>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
