// @generated by Metrics Storybook story generator
// @source-hash: ecdeabfb1779e967

import type { Meta, StoryObj } from "@storybook/react-vite";

import { DropdownMenuIcons } from "./dropdown-menu-icons";

const meta = {
  title: "Primitives/Dropdowns/Dropdown Menu Icons",
  component: DropdownMenuIcons,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof DropdownMenuIcons>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
