// @generated by Metrics Storybook story generator
// @source-hash: 6c3a18839bc3bccc

import type { Meta, StoryObj } from "@storybook/react-vite";

import { DropdownMenuBasic } from "./dropdown-menu-basic";

const meta = {
  title: "Primitives/Dropdowns/Dropdown Menu Basic",
  component: DropdownMenuBasic,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof DropdownMenuBasic>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
