// @generated by Metrics Storybook story generator
// @source-hash: 33c3fd355a5e162e

import type { Meta, StoryObj } from "@storybook/react-vite";

import { DropdownMenuRadioGroupDemo } from "./dropdown-menu-radio-group";

const meta = {
  title: "Primitives/Dropdowns/Dropdown Menu Radio Group Demo",
  component: DropdownMenuRadioGroupDemo,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof DropdownMenuRadioGroupDemo>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
