// @generated by Metrics Storybook story generator
// @source-hash: 9fd7fda6f72f1ea4

import type { Meta, StoryObj } from "@storybook/react";

import { DropdownMenuDestructive } from "./dropdown-menu-destructive";

const meta = {
  title: "Primitives/Dropdowns/Dropdown Menu Destructive",
  component: DropdownMenuDestructive,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof DropdownMenuDestructive>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
