// @generated by Metrics Storybook story generator
// @source-hash: 88e97796578ac18d

import type { Meta, StoryObj } from "@storybook/react-vite";

import { DropdownMenuCheckboxesIcons } from "./dropdown-menu-checkboxes-icons";

const meta = {
  title: "Primitives/Dropdowns/Dropdown Menu Checkboxes Icons",
  component: DropdownMenuCheckboxesIcons,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof DropdownMenuCheckboxesIcons>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
