// @generated by Metrics Storybook story generator
// @source-hash: 80adc0ae2870c611

import type { Meta, StoryObj } from "@storybook/react-vite";

import { DropdownMenuCheckboxes } from "./dropdown-menu-checkboxes";

const meta = {
  title: "Primitives/Dropdowns/Dropdown Menu Checkboxes",
  component: DropdownMenuCheckboxes,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof DropdownMenuCheckboxes>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
