// @generated by Metrics Storybook story generator
// @source-hash: c103afde580146fe

import type { Meta, StoryObj } from "@storybook/react-vite";

import { SelectDropdown } from "./select-dropdown";

const meta = {
  title: "Primitives/Dropdowns/Select Dropdown",
  component: SelectDropdown,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {
    defaultValue: "Default Value",
    items: "Items",
  },
} satisfies Meta<typeof SelectDropdown>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
