// @generated by Metrics Storybook story generator
// @source-hash: e1f4a1bda2047f2d

import type { Meta, StoryObj } from "@storybook/react-vite";

import { TwentyTwelveOne } from "./smooth-dropdown";

const meta = {
  title: "Primitives/Dropdowns/Twenty Twelve One",
  component: TwentyTwelveOne,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof TwentyTwelveOne>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
