// @generated by Metrics Storybook story generator
// @source-hash: 00b96bd10def6c4e

import type { Meta, StoryObj } from "@storybook/react-vite";

import { AccountForm } from "./account_form";

const meta = {
  title: "Components/Metrics Layouts/Settings/Account Form",
  component: AccountForm,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof AccountForm>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
