// @generated by Metrics Storybook story generator
// @source-hash: 2cb001a1d6b1d21b

import type { Meta, StoryObj } from "@storybook/react-vite";

import { SettingsNotificationsPage } from "./notifications_page";

const meta = {
  title: "Components/Metrics Layouts/Settings/Settings Notifications Page",
  component: SettingsNotificationsPage,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof SettingsNotificationsPage>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
