// @generated by Metrics Storybook story generator
// @source-hash: 59a8d5639f9f7572

import type { Meta, StoryObj } from "@storybook/react-vite";

import { SettingsPage } from "./settings_layout";

const meta = {
  title: "Components/Metrics Layouts/Settings/Settings Page",
  component: SettingsPage,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof SettingsPage>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
