// @generated by Metrics Storybook story generator
// @source-hash: 5609823ee6734507

import type { Meta, StoryObj } from "@storybook/react";

import { ImageEditBlock } from "./image-edit-block";

const meta = {
  title: "Primitives/Image Blocks/Image Edit Block",
  component: ImageEditBlock,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ImageEditBlock>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
