// @generated by Metrics Storybook story generator
// @source-hash: cf6fb7947358e9ef

// TODO(story): Provide representative values for required props:
// - editor: Editor
import type { Meta, StoryObj } from "@storybook/react";

import { ImageEditDialog } from "./image-edit-dialog";

const meta = {
  title: "Primitives/Image Blocks/Image Edit Dialog",
  component: ImageEditDialog,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ImageEditDialog>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
