// @generated by Metrics Storybook story generator
// @source-hash: 03a7cbbecbc05b13

import type { Meta, StoryObj } from "@storybook/react";

import { PopoverAlignments } from "./popover-alignments";

const meta = {
  title: "Primitives/Popovers/Popover Alignments",
  component: PopoverAlignments,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof PopoverAlignments>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
