// @generated by Metrics Storybook story generator
// @source-hash: f23616868c2536cf

import type { Meta, StoryObj } from "@storybook/react";

import { PopoverForm } from "./popover-form";

const meta = {
  title: "Primitives/Popovers/Popover Form",
  component: PopoverForm,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof PopoverForm>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
