// @generated by Metrics Storybook story generator
// @source-hash: 7c0f021bb9fde963

import type { Meta, StoryObj } from "@storybook/react-vite";

import { PopoverBasic } from "./popover-basic";

const meta = {
  title: "Primitives/Popovers/Popover Basic",
  component: PopoverBasic,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof PopoverBasic>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
