// @generated by Metrics Storybook story generator
// @source-hash: 273f08c0dcdba361

import type { Meta, StoryObj } from "@storybook/react-vite";

import { PopoverTrigger } from "./popover";

const meta = {
  title: "Primitives/Popovers/Popover Trigger",
  component: PopoverTrigger,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof PopoverTrigger>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
