// @generated by Metrics Storybook story generator
// @source-hash: d1d0afb1a3b4537b

import type { Meta, StoryObj } from "@storybook/react-vite";

import { AreaChartDemo } from "./chart-demos";

const meta = {
  title: "Primitives/Charts/Area Chart Demo",
  component: AreaChartDemo,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof AreaChartDemo>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
