// @generated by Metrics Storybook story generator
// @source-hash: 90535c7c075cf43f

// TODO(story): Provide representative values for required props:
// - config: ChartConfig
import type { Meta, StoryObj } from "@storybook/react";

import { ChartContainer } from "./chart";

const meta = {
  title: "Primitives/Charts/Chart Container",
  component: ChartContainer,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {
    children: "Chart Container",
  },
} satisfies Meta<typeof ChartContainer>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
