// @generated by Metrics Storybook story generator
// @source-hash: e7a6206fccf56a44

// TODO(story): Provide representative values for required props:
// - activeView: GrowthPlanView
import type { Meta, StoryObj } from "@storybook/react-vite";

import { GrowthPlanViewSwitcher } from "./growth-plan-view_switcher";

const meta = {
  title: "Components/Metrics Layouts/Tasks/Growth Plan View Switcher",
  component: GrowthPlanViewSwitcher,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {
    onViewChange: () => {},
  },
} satisfies Meta<typeof GrowthPlanViewSwitcher>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
