// @generated by Metrics Storybook story generator
// @source-hash: 505c6cec03965883

import type { Meta, StoryObj } from "@storybook/react-vite";

import { TasksMutateDrawer } from "./tasks-mutate_drawer";

const meta = {
  title: "Components/Metrics Layouts/Tasks/Tasks Mutate Drawer",
  component: TasksMutateDrawer,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {
    open: false,
    onOpenChange: () => {},
  },
} satisfies Meta<typeof TasksMutateDrawer>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
