import { readdirSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import type { StorybookConfig } from "@storybook/react-vite";
import { mergeConfig } from "vite";
import tsconfigPaths from "vite-tsconfig-paths";

const configDirectory = dirname(fileURLToPath(import.meta.url));
const repositoryRoot = resolve(configDirectory, "../../..");
const uiSourceDirectory = resolve(repositoryRoot, "packages/ui/src");
const generatedStoryMarker =
  "// @generated by Metrics Storybook story generator";

function findCuratedStories(directory: string): string[] {
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const path = resolve(directory, entry.name);

    if (entry.isDirectory()) {
      return findCuratedStories(path);
    }

    if (!entry.name.match(/\.stories\.(js|jsx|mjs|ts|tsx)$/)) {
      return [];
    }

    return readFileSync(path, "utf8").startsWith(generatedStoryMarker)
      ? []
      : [path];
  });
}

const config: StorybookConfig = {
  stories: findCuratedStories(uiSourceDirectory),
  staticDirs: [
    {
      from: resolve(repositoryRoot, "packages/ui/src/fonts"),
      to: "/assets",
    },
  ],
  addons: ["@storybook/addon-docs", "@storybook/addon-a11y"],
  framework: {
    name: "@storybook/react-vite",
    options: {},
  },
  async viteFinal(currentConfig) {
    return mergeConfig(currentConfig, {
      server: {
        allowedHosts: ["localhost", "127.0.0.1"],
      },
      plugins: [
        tsconfigPaths({
          projects: [resolve(repositoryRoot, "tsconfig.json")],
        }),
      ],
    });
  },
};

export default config;
