// @generated by Metrics Storybook story generator
// @source-hash: 00559eb945163894

import type { Meta, StoryObj } from "@storybook/react-vite";

import { PasswordInput } from "./password-input";

const meta = {
  title: "Primitives/Users/Password Input",
  component: PasswordInput,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof PasswordInput>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
