// @generated by Metrics Storybook story generator
// @source-hash: 8b383d01c0a2f202

import type { Meta, StoryObj } from "@storybook/react-vite";

import { ProfileDropdown } from "./profile-dropdown";

const meta = {
  title: "Primitives/Users/Profile Dropdown",
  component: ProfileDropdown,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ProfileDropdown>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
