// @generated by Metrics Storybook story generator
// @source-hash: 810ce6e1c636d027

import type { Meta, StoryObj } from "@storybook/react";

import { SignOutDialog } from "./sign-out-dialog";

const meta = {
  title: "Primitives/Users/Sign Out Dialog",
  component: SignOutDialog,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {
    open: false,
    onOpenChange: () => {},
  },
} satisfies Meta<typeof SignOutDialog>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
