// @generated by Metrics Storybook story generator
// @source-hash: a976c477bd3a7f87

import type { Meta, StoryObj } from "@storybook/react-vite";

import { Login } from "./login";

const meta = {
  title: "Primitives/Users/Login",
  component: Login,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof Login>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
