# -*- coding: utf-8 -*-
"""Step06_StayInTouch_UploadBiquery.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qaqdb828WR1l48JdU_-Z7YSy87p-1nX5

## Gemini Master Instructions for Modular Colab **Workflows**

You are helping design and maintain **modular Google Colab workflows** orchestrated by a **central master pipeline**. Every notebook step must remain self-contained, reusable, and easy to debug independently, while still fitting into a larger end-to-end workflow. Make sure to read and follow the guidance below.

---

### 1. Core Architecture Principles

* Build workflows as **modular processing blocks**.
* Each major step must be **self-contained** with clear inputs/outputs.
* Use a **single master pipeline block** to orchestrate execution.
* Avoid tight coupling between modules.
* Prefer explicit data handoffs (dataframes, return values, or defined globals).
* Design modules so they can be **tested independently**.

---

### 2. Variable Management Rules

* **Consolidate all variables within the master pipeline block.**
* If variables are needed elsewhere, **import them as globals**.
* Do not scatter configuration values across cells.
* Avoid duplicate constants inside modules.
* Add new variables to the master pipeline first, then wire downstream.

---

### 3. Notes and Commentary

* **Preserve all notes exactly where they are placed.**
* Do not remove or rewrite notes unless explicitly instructed.
* Treat markdown and comments as long-term documentation.
* Flag outdated notes instead of deleting them.

---

### 4. Notebook Structure

Preferred order:

1. Preflight / setup
2. Authentication / mounts
3. Shared imports
4. Module sections
5. Validation / diagnostics
6. Export / outputs
7. Master pipeline
8. Utility / recovery helpers

Use clear section headers (e.g., `### Preflight Check`, `# Master Pipeline`).

---

### 5. Module Design Requirements

* Each module should have **one responsibility**.
* Wrap logic in clearly named functions.
* Define inputs and outputs explicitly.
* Avoid hidden dependencies.
* Include lightweight validation.
* Document side effects (exports, file moves, etc.).

---

## 6. Master Pipeline Responsibilities

The master pipeline must:

* Define all variables and configuration
* Control execution order
* Pass configuration to modules
* Handle global state intentionally
* Manage logging and status
* Coordinate exports and failure handling

---

### 7. Globals Usage Rules

* Use globals only for intentionally shared configuration.
* Assign globals in the master pipeline.
* Avoid implicit globals in modules.
* Make dependencies on globals explicit.

---

### 8. Imports and Dependencies

* Keep imports organized.
* Avoid unnecessary duplication.
* Include imports in modules only if needed for isolation.
* Do not introduce unnecessary libraries.

---

### 9. Validation and Debugging

* Add validation checkpoints after transformations.
* Include diagnostics (row counts, schema checks, etc.).
* Print clear status messages.
* Fail gracefully where possible.

---

### 10. Output and Export Standards

* Keep export logic in a dedicated section.
* Use clear, traceable naming conventions.
* Avoid hidden output paths.
* Document outputs clearly.

---

### 11. Recovery and Utility Cells

* Keep utilities separate from core workflow.
* Clearly label recovery logic.
* Preserve existing utility cells.

---

### 12. Change Management

* Preserve structure unless improvement is necessary.
* Do not collapse modular design.
* Prefer targeted edits.
* Explain structural changes when needed.

---

### 13. Coding Style

* Write readable, maintainable code.
* Use clear function names.
* Prefer explicit logic over shortcuts.
* Preserve dataframe clarity.

---

### 14. Interaction Rules

When building workflows:

* Assume modular architecture is required.
* Place variables in the master pipeline.
* Preserve notes and structure.
* Return code ready for direct cell insertion.
* Highlight impacted sections when making changes.

---

### Short Instruction Block (Reusable)

```text
Build this Colab workflow using a modular notebook architecture.

Rules:
1. Consolidate all variables within the master pipeline block.
2. Import shared variables as globals when needed.
3. Preserve all notes and markdown exactly as placed.
4. Keep each module self-contained and reusable.
5. Use a master pipeline for orchestration.
6. Do not scatter configuration values.
7. Maintain clear section headers.
8. Separate validation, export, and recovery logic.
9. Prefer targeted updates over rewrites.
10. Write maintainable, debuggable code.
```

### DATA EXTRACTION LOGIC

Do not use hard-coded row numbers or fixed positional logic when parsing these reports. Instead, use anchor-based detection by defining constants for known header or label text, such as const headers = ['Occ (%)', 'Index (MPI)', ...], and locate rows dynamically based on those anchors. This ensures the parser remains stable even if rows shift between properties, report versions, or months.

The parsing logic should always identify the relevant section by searching for the expected text labels in the sheet, rather than assuming a metric will always appear on the same row. Build the mapping from those discovered anchor points, then derive the related values relative to the matched labels. This makes the pipeline more resilient and reduces breakage when report formatting changes.

Use anchor-based parsing only. Never rely on fixed row indexes for report extraction. Define reusable constants for expected labels and headers, scan the sheet to find those anchors, and build mappings from the discovered positions. This ensures the parser continues to work even when report layouts shift.
"""

import os

# Get the NEW_DIR from the previously defined global variable
# Ensure the variable is accessible or redefine if necessary for standalone check
# Assuming NEW_DIR is already defined and accessible from cell 82NZo4IF_5ts



if 'NEW_DIR' in globals():
    print(f"Listing contents of: {NEW_DIR}")
    if os.path.exists(NEW_DIR):
        files_in_dir = os.listdir(NEW_DIR)
        if files_in_dir:
            for f in files_in_dir:
                print(f"- {f}")
        else:
            print("The directory is empty.")
    else:
        print(f"Error: Directory not found at {NEW_DIR}")
else:
    print("Error: NEW_DIR variable is not defined. Please run the setup cell (82NZo4IF_5ts) first.")

# @title Default title text

from google.colab import drive
import os

# --- HELPER FUNCTIONS FOR SETUP ---
def initialize_client(project_id):
    """Initializes the BigQuery client."""
    # BigQuery client initialization is removed as per user request
    pass # No-op or remove if function is no longer needed at all

# --- SETUP & AUTH ---
drive.mount('/content/drive')

# --- CONFIGURATION (Master Variables) ---
global SOURCE_DIR, NEW_DIR, PROCESSED_DIR, EXPORT_DIR, FAILED_DIR

SOURCE_DIR = "/content/drive/Shareddrives/ClientHubs/Dovetail&Co/data_pipeline/process_step05" # @param {"type":"string","placeholder":"/content/drive/Shareddrives/Client Hubs/Dovetail&Co/data_pipeline/process_step05"}
NEW_DIR = os.path.join(SOURCE_DIR, "data_upload")
PROCESSED_DIR = os.path.join(SOURCE_DIR, "data_processed")
EXPORT_DIR = os.path.join(SOURCE_DIR, "data_export")
FAILED_DIR = os.path.join(SOURCE_DIR, "data_failed")

# Create the necessary folders if they don't exist
if not os.path.exists(NEW_DIR):
    os.makedirs(NEW_DIR)
    print(f"Created directory: {NEW_DIR}")
if not os.path.exists(PROCESSED_DIR):
    os.makedirs(PROCESSED_DIR)
    print(f"Created directory: {PROCESSED_DIR}")
if not os.path.exists(EXPORT_DIR):
    os.makedirs(EXPORT_DIR)
    print(f"Created directory: {EXPORT_DIR}")
if not os.path.exists(FAILED_DIR):
    os.makedirs(FAILED_DIR)
    print(f"Created directory: {FAILED_DIR}")

print(f"Checking for new files in: {NEW_DIR}")

# BigQuery client initialization removed as per user request
# client = initialize_client(PROJECT_ID)
# print("BigQuery client initialized.")

"""# Setup & Auth"""

# @title Connect to Google Drive {"vertical-output":true,"single-column":true,"display-mode":"code"}

from google.colab import drive
import os

# --- SETUP & AUTH ---
# Use force_remount=True to attempt a fresh connection if it previously failed
try:
    drive.mount('/content/drive', force_remount=True)
    print("Drive mounted successfully.")
except Exception as e:
    print(f"Manual action required: Please click the Drive icon in the left file pane to mount your drive. Error: {e}")

# --- CONFIGURATION (Master Variables) ---
global SOURCE_DIR, NEW_DIR, PROCESSED_DIR, EXPORT_DIR, FAILED_DIR, NEXT_DIR

SOURCE_DIR = "/content/drive/Shareddrives/ClientHubs/Dovetail&Co/data_pipeline/process_step03" # @param {"type":"string","placeholder":"/content/drive/Shareddrives/Client Hubs/Dovetail&Co/data_pipeline/process_step03"}
NEXT_DIR = "/content/drive/Shareddrives/ClientHubs/Dovetail&Co/data_pipeline/process_step04" # @param {"type":"string","placeholder":"/content/drive/Shareddrives/Client Hubs/Dovetail&Co/data_pipeline/process_step04"}

NEW_DIR = os.path.join(SOURCE_DIR, "data_upload")
PROCESSED_DIR = os.path.join(SOURCE_DIR, "data_processed")
EXPORT_DIR = os.path.join(SOURCE_DIR, "data_export")
FAILED_DIR = os.path.join(SOURCE_DIR, "data_failed")
NEXT_DIR = os.path.join(NEXT_DIR, "data_upload")

# Create the necessary folders if they don't exist
if not os.path.exists(NEW_DIR):
    os.makedirs(NEW_DIR)
    print(f"Created directory: {NEW_DIR}")
if not os.path.exists(PROCESSED_DIR):
    os.makedirs(PROCESSED_DIR)
    print(f"Created directory: {PROCESSED_DIR}")
if not os.path.exists(EXPORT_DIR):
    os.makedirs(EXPORT_DIR)
    print(f"Created directory: {EXPORT_DIR}")
if not os.path.exists(FAILED_DIR):
    os.makedirs(FAILED_DIR)
    print(f"Created directory: {FAILED_DIR}")

print(f"Checking for new files in: {NEW_DIR}")

"""# Process File"""

import glob
import os, shutil, re
import pandas as pd
import numpy as np
from google.colab import drive

# --- HELPER FUNCTIONS ---
def standardize_headers(df, column_mapping=None):
    # Define columns to be dropped
    columns_to_drop = [
        'Hotel Code',
        'Market Id',
        'Source Id',
        'Room Type Id',
        'Room Id',
        'Allotment Id',
        'Group Id',
        'Posting Account Id',
        'Booking origin Id',
        'segment_id'
    ]

    # Drop specified columns if they exist
    existing_columns_to_drop = [col for col in columns_to_drop if col in df.columns]
    if existing_columns_to_drop:
        df = df.drop(columns=existing_columns_to_drop)
        print(f"  Dropped columns: {existing_columns_to_drop}")

    # Use the external standardizer if available
    if 'revrebel_standardizer' in globals():
        try:
            df = revrebel_standardizer.standardize_columns(df)
            print("  Applied revrebel_standardizer normalization.")
        except Exception as e:
            print(f"  Warning: External standardizer failed ({e}), falling back to basic cleaning.")
            df.columns = [
                col.lower().strip().replace('/', '_').replace(' ', '_').replace('.', '').replace('-', '_').replace('__', '_')
                for col in df.columns
            ]
    else:
        df.columns = [
            col.lower().strip().replace('/', '_').replace(' ', '_').replace('.', '').replace('-', '_').replace('__', '_')
            for col in df.columns
        ]
    return df

def find_header_row(file_path, keywords=["confirmation_number", "hotel_code", "arrival_date"]):
    """Finds the header row by counting matches for target keywords."""
    best_row = 0
    max_matches = 0
    with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
        for i, line in enumerate(f):
            if i > 50: break
            matches = sum(1 for word in keywords if word.lower() in line.lower())
            if matches > max_matches:
                max_matches = matches
                best_row = i
            if max_matches >= len(keywords):
                return i
    return best_row

# --- 5. MASTER PIPELINE ---
def run_master_pipeline():
    search_path = os.path.join(NEW_DIR, "*.csv")
    files_to_process = glob.glob(search_path)

    if not files_to_process:
        # Check if we need to pull back from Processed for this run (for testing/demo)
        print("No files in Upload. Checking Processed/Failed for re-processing...")
        for folder in [PROCESSED_DIR, FAILED_DIR]:
            if os.path.exists(folder):
                for f_name in os.listdir(folder):
                    if f_name.endswith('.csv') and "combined_standardized" not in f_name:
                        shutil.move(os.path.join(folder, f_name), os.path.join(NEW_DIR, f_name))
        files_to_process = glob.glob(search_path)

    print(f"Found {len(files_to_process)} files to analyze.")
    all_standardized_dfs = []

    for file_path in files_to_process:
        file_name = os.path.basename(file_path)
        print(f"\nProcessing: {file_name}")

        # Parse Date and Property Code for Filename naming
        # Regex looks for YYYYMMDD and the alphanumeric code following it
        name_match = re.search(r"(\d{8})_([A-Z0-9]+)", file_name, re.IGNORECASE)
        if name_match:
            snap_date_raw = name_match.group(1)
            prop_code = name_match.group(2).upper()
            snap_date_str = pd.to_datetime(snap_date_raw, format="%Y%m%d").strftime("%Y-%m-%d")
            output_filename = f"{snap_date_raw}_{prop_code}_combined_standardized.csv"
        else:
            snap_date_str     = "UNKNOWN"
            prop_code         = "UNKNOWN"
            output_filename   = "combined_standardized_data.csv"

        try:
            header_idx = find_header_row(file_path)
            df = pd.read_csv(file_path, delimiter=',', header=header_idx, on_bad_lines='skip', low_memory=False)

            df_std = standardize_headers(df)
            df_std['property_code'] = prop_code
            df_std['source_file'] = file_name
            df_std['snap_date'] = snap_date_str

            # Save individual standardized file with new naming convention
            export_path = os.path.join(EXPORT_DIR, output_filename)
            df_std.to_csv(export_path, index=False)

            all_standardized_dfs.append(df_std)
            print(f"  ✅ Success: {prop_code} | Exported to: {output_filename}")
            shutil.move(file_path, os.path.join(PROCESSED_DIR, file_name))

        except Exception as e:
            print(f"  ❌ Error: {e}")
            shutil.move(file_path, os.path.join(FAILED_DIR, file_name))

if __name__ == "__main__":
    run_master_pipeline()

"""### Verify Columns and First 10 Rows of a Sample File

This cell will pick the first CSV file found in the `Data_Upload` directory, apply the `pd.read_csv` logic with `delimiter=','` and `header=3`, and display the resulting DataFrame's columns and the first 10 rows. This helps verify that the parsing is working as expected.
"""

import os
import pandas as pd

# Look for the combined file in the Export directory
combined_file_path = os.path.join(EXPORT_DIR, "combined_standardized_data.csv")

if os.path.exists(combined_file_path):
    print(f"Verifying combined file: {combined_file_path}")
    try:
        # Read the file with low_memory=False to ensure type consistency
        df_check = pd.read_csv(combined_file_path, low_memory=False)

        print("\n--- Data Quality Summary (Standardized Schema) ---")
        print(f"Total Rows: {len(df_check)}")

        # Updated to check the NEW standardized column names from the library
        check_cols = [
            'rate_amount',
            'original_rate',
            'amount',
            'first_night_price',
            'last_night_price'
        ]

        for col in check_cols:
            if col in df_check.columns:
                non_null = df_check[col].count()
                pct = (non_null / len(df_check)) * 100
                print(f"Column '{col}': {non_null} non-null values ({pct:.1f}%) Kishan)")
            else:
                print(f"Column '{col}': NOT FOUND (Check standardizer mapping)")

        print("\n--- Sample of Populated Rows (rate_amount) ---")
        if 'rate_amount' in df_check.columns:
            # Displaying rows where rate_amount is populated to ensure the NaN error is solved
            populated_sample = df_check[df_check['rate_amount'].notna()].head(10)
            if not populated_sample.empty:
                display(populated_sample)
            else:
                print("No rows found with populated rate_amount.")

    except Exception as e:
        print(f"❌ Error reading the combined file: {e}")
else:
    print(f"Combined file not found at: {combined_file_path}. Please run the master pipeline cell (zDkwBwlw-CyM) first.")