// @generated by Metrics Storybook story generator
// @source-hash: 71b92848a0e0eec8

import type { Meta, StoryObj } from "@storybook/react-vite";

import { TypographyList } from "./TypographyList";

const meta = {
  title: "Primitives/Typography/Typography List",
  component: TypographyList,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof TypographyList>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
