// @generated by Metrics Storybook story generator
// @source-hash: 8e14d810d5e2ea0e

import type { Meta, StoryObj } from "@storybook/react-vite";

import { TypographyLead } from "./TypographyLead";

const meta = {
  title: "Primitives/Typography/Typography Lead",
  component: TypographyLead,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof TypographyLead>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
