// @generated by Metrics Storybook story generator
// @source-hash: 210eb44c4f86d258

import type { Meta, StoryObj } from "@storybook/react";

import { TypographyH4 } from "./TypographyH4";

const meta = {
  title: "Primitives/Typography/Typography H4",
  component: TypographyH4,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof TypographyH4>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
