// @generated by Metrics Storybook story generator
// @source-hash: 4819e6396ed4b3d7

import type { Meta, StoryObj } from "@storybook/react";

import { TypographyH2 } from "./TypographyH2";

const meta = {
  title: "Primitives/Typography/Typography H2",
  component: TypographyH2,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof TypographyH2>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
