// @generated by Metrics Storybook story generator
// @source-hash: d7ae4e2603d15c7e

import type { Meta, StoryObj } from "@storybook/react";

import { TypographyH3 } from "./TypographyH3";

const meta = {
  title: "Primitives/Typography/Typography H3",
  component: TypographyH3,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof TypographyH3>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
