// @generated by Metrics Storybook story generator
// @source-hash: a7d3ec19b4ed20e7

import type { Meta, StoryObj } from "@storybook/react-vite";

import { TypographyH5 } from "./TypographyH5";

const meta = {
  title: "Primitives/Typography/Typography H5",
  component: TypographyH5,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof TypographyH5>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
