// @generated by Metrics Storybook story generator
// @source-hash: 52cc610ecc6316f1

import type { Meta, StoryObj } from "@storybook/react-vite";

import { TypographyH1 } from "./TypographyH1";

const meta = {
  title: "Primitives/Typography/Typography H1",
  component: TypographyH1,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof TypographyH1>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
