// @generated by Metrics Storybook story generator
// @source-hash: 1b075bdc10e16a61

import type { Meta, StoryObj } from "@storybook/react-vite";

import { TypographyTable } from "./TypographyTable";

const meta = {
  title: "Primitives/Typography/Typography Table",
  component: TypographyTable,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof TypographyTable>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
