// @generated by Metrics Storybook story generator
// @source-hash: 0eb25e55af02a932

import type { Meta, StoryObj } from "@storybook/react-vite";

import { TypographyLarge } from "./TypographyLarge";

const meta = {
  title: "Primitives/Typography/Typography Large",
  component: TypographyLarge,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof TypographyLarge>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
