// @generated by Metrics Storybook story generator
// @source-hash: 6ed38219856cfce8

import type { Meta, StoryObj } from "@storybook/react";

import { TypographyP } from "./TypographyP";

const meta = {
  title: "Primitives/Typography/Typography P",
  component: TypographyP,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof TypographyP>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
