// @generated by Metrics Storybook story generator
// @source-hash: dd9364f6f9ae7793

import type { Meta, StoryObj } from "@storybook/react";

import { TypographySmall } from "./TypographySmall";

const meta = {
  title: "Primitives/Typography/Typography Small",
  component: TypographySmall,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof TypographySmall>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
