// @generated by Metrics Storybook story generator
// @source-hash: 8f9762afa813a1eb

import type { Meta, StoryObj } from "@storybook/react-vite";

import { TypographyBlockquote } from "./TypographyBlockquoteProps";

const meta = {
  title: "Primitives/Typography/Typography Blockquote",
  component: TypographyBlockquote,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof TypographyBlockquote>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
