// @generated by Metrics Storybook story generator
// @source-hash: 8a960c6ee0fc3549

import type { Meta, StoryObj } from "@storybook/react-vite";

import { TypographyMuted } from "./TypographyMuted";

const meta = {
  title: "Primitives/Typography/Typography Muted",
  component: TypographyMuted,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof TypographyMuted>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
