// @generated by Metrics Storybook story generator
// @source-hash: 74c3b1bd887dd7a3

import type { Meta, StoryObj } from "@storybook/react";

import { TypographyInlineCode } from "./TyypographyLineCode";

const meta = {
  title: "Primitives/Typography/Typography Inline Code",
  component: TypographyInlineCode,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof TypographyInlineCode>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
