// @generated by Metrics Storybook story generator
// @source-hash: 42a301d338c33a0b

import type { Meta, StoryObj } from "@storybook/react-vite";

import { FormItem } from "./form";

const meta = {
  title: "Primitives/Forms/Form Item",
  component: FormItem,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof FormItem>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
