// @generated by Metrics Storybook story generator
// @source-hash: 93fe7b83f8983abf

import type { Meta, StoryObj } from "@storybook/react-vite";

import { SettingsAccountPage } from "./account_page";

const meta = {
  title: "Components/Metrics Layouts/Settings/Settings Account Page",
  component: SettingsAccountPage,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof SettingsAccountPage>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
