// @generated by Metrics Storybook story generator
// @source-hash: e8e7cc29f0c76bc0

import type { Meta, StoryObj } from "@storybook/react-vite";

import { ContentSection } from "./content-section_page";

const meta = {
  title: "Components/Metrics Layouts/Settings/Content Section",
  component: ContentSection,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {
    title: "Title",
    desc: "Desc",
    children: "Content Section",
  },
} satisfies Meta<typeof ContentSection>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
