// @generated by Metrics Storybook story generator
// @source-hash: ac5451643bbfa2fd

import type { Meta, StoryObj } from "@storybook/react-vite";

import { DisplayForm } from "./display_form";

const meta = {
  title: "Components/Metrics Layouts/Settings/Display Form",
  component: DisplayForm,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof DisplayForm>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
