// @generated by Metrics Storybook story generator
// @source-hash: a5758a3b497aac3a

import type { Meta, StoryObj } from "@storybook/react";

import { SettingsDisplayPage } from "./display_page";

const meta = {
  title: "Components/Metrics Layouts/Settings/Settings Display Page",
  component: SettingsDisplayPage,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof SettingsDisplayPage>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
