// @generated by Metrics Storybook story generator
// @source-hash: 75fc940c0564e761

import type { Meta, StoryObj } from "@storybook/react";

import { NotificationsForm } from "./notifications_form";

const meta = {
  title: "Components/Metrics Layouts/Settings/Notifications Form",
  component: NotificationsForm,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof NotificationsForm>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
