// @generated by Metrics Storybook story generator
// @source-hash: 61b18f69a265dbf7

import type { Meta, StoryObj } from "@storybook/react-vite";

import { ProfileForm } from "./profile_form";

const meta = {
  title: "Components/Metrics Layouts/Settings/Profile Form",
  component: ProfileForm,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ProfileForm>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
