// @generated by Metrics Storybook story generator
// @source-hash: 0c21cba581f2a13f

import type { Meta, StoryObj } from "@storybook/react-vite";

import { SettingsProfilePage } from "./profile_page";

const meta = {
  title: "Components/Metrics Layouts/Settings/Settings Profile Page",
  component: SettingsProfilePage,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof SettingsProfilePage>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
