// @generated by Metrics Storybook story generator
// @source-hash: 20558ed768113b59

import type { Meta, StoryObj } from "@storybook/react-vite";

import { SidebarNav } from "./settings_sidebar-nav";

const meta = {
  title: "Components/Metrics Layouts/Settings/Sidebar Nav",
  component: SidebarNav,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {
    items: "Items",
  },
} satisfies Meta<typeof SidebarNav>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
