// @generated by Metrics Storybook story generator
// @source-hash: fd468a4da2dd42ab

import type { Meta, StoryObj } from "@storybook/react";

import { UsersInviteDialog } from "./users-invite_dialog";

const meta = {
  title: "Components/Metrics Layouts/Settings/Users Invite Dialog",
  component: UsersInviteDialog,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {
    open: false,
    onOpenChange: () => {},
  },
} satisfies Meta<typeof UsersInviteDialog>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
