// @generated by Metrics Storybook story generator
// @source-hash: 5e7a69a621738392

import type { Meta, StoryObj } from "@storybook/react";

import { SectionFive } from "./five";

const meta = {
  title: "Primitives/Sections/Section Five",
  component: SectionFive,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof SectionFive>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
