// @generated by Metrics Storybook story generator
// @source-hash: f947117bd4342c13

import type { Meta, StoryObj } from "@storybook/react-vite";

import { SectionFour } from "./four";

const meta = {
  title: "Primitives/Sections/Section Four",
  component: SectionFour,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof SectionFour>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
