// @generated by Metrics Storybook story generator
// @source-hash: 784a0d11cfbe5151

import type { Meta, StoryObj } from "@storybook/react-vite";

import { SectionOne } from "./one";

const meta = {
  title: "Primitives/Sections/Section One",
  component: SectionOne,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof SectionOne>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
