// @generated by Metrics Storybook story generator
// @source-hash: 67d0c8c2dacf4b36

import type { Meta, StoryObj } from "@storybook/react-vite";

import { ShortcutKey } from "./shortcut-key";

const meta = {
  title: "Primitives/Sections/Shortcut Key",
  component: ShortcutKey,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ShortcutKey>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
