// @generated by Metrics Storybook story generator
// @source-hash: aa5750a9ee5df420

import type { Meta, StoryObj } from "@storybook/react-vite";

import { SectionThree } from "./three";

const meta = {
  title: "Primitives/Sections/Section Three",
  component: SectionThree,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof SectionThree>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
