// @generated by Metrics Storybook story generator
// @source-hash: eb4a401b14f174db

import type { Meta, StoryObj } from "@storybook/react-vite";

import { ToolbarSection } from "./toolbar-section";

const meta = {
  title: "Primitives/Sections/Toolbar Section",
  component: ToolbarSection,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ToolbarSection>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
