// @generated by Metrics Storybook story generator
// @source-hash: a13126129867754b

import type { Meta, StoryObj } from "@storybook/react";

import { SectionTwo } from "./two";

const meta = {
  title: "Primitives/Sections/Section Two",
  component: SectionTwo,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof SectionTwo>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
