// @generated by Metrics Storybook story generator
// @source-hash: 049a4076812130e4

import type { Meta, StoryObj } from "@storybook/react-vite";

import { Accordion } from "./accordion";

const meta = {
  title: "Primitives/Ui Core/Accordion",
  component: Accordion,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof Accordion>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
