// @generated by Metrics Storybook story generator
// @source-hash: 2d407f2ec56d1f0c

import type { Meta, StoryObj } from "@storybook/react-vite";

import { AlertDialog } from "./alert-dialog";

const meta = {
  title: "Primitives/Ui Core/Alert Dialog",
  component: AlertDialog,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof AlertDialog>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
