// @generated by Metrics Storybook story generator
// @source-hash: 7f0e4b79f14849ab

import type { Meta, StoryObj } from "@storybook/react";

import { Calendar } from "./calendar";

const meta = {
  title: "Primitives/Ui Core/Calendar",
  component: Calendar,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof Calendar>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
