// @generated by Metrics Storybook story generator
// @source-hash: 840b90a3285bc7b6

import type { Meta, StoryObj } from "@storybook/react-vite";

import { Carousel } from "./carousel";

const meta = {
  title: "Primitives/Ui Core/Carousel",
  component: Carousel,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof Carousel>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
