// @generated by Metrics Storybook story generator
// @source-hash: a87d6aa9405ad09b

import type { Meta, StoryObj } from "@storybook/react-vite";

import { Collapsible } from "./collapsible";

const meta = {
  title: "Primitives/Ui Core/Collapsible",
  component: Collapsible,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof Collapsible>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
