// @generated by Metrics Storybook story generator
// @source-hash: 947fba87706687d8

import type { Meta, StoryObj } from "@storybook/react";

import { Combobox } from "./combobox";

const meta = {
  title: "Primitives/Ui Core/Combobox",
  component: Combobox,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof Combobox>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
