// @generated by Metrics Storybook story generator
// @source-hash: 4d898b113172b919

import type { Meta, StoryObj } from "@storybook/react";

import { CommandMenu } from "./command-menu";

const meta = {
  title: "Primitives/Ui Core/Command Menu",
  component: CommandMenu,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof CommandMenu>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
