// @generated by Metrics Storybook story generator
// @source-hash: 082efa45359266dd

import type { Meta, StoryObj } from "@storybook/react";

import { Command } from "./command";

const meta = {
  title: "Primitives/Ui Core/Command",
  component: Command,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof Command>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
