// @generated by Metrics Storybook story generator
// @source-hash: 5854ff6d8eeb39cb

import type { Meta, StoryObj } from "@storybook/react-vite";

import { ConfigDrawer } from "./config-drawer";

const meta = {
  title: "Primitives/Ui Core/Config Drawer",
  component: ConfigDrawer,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ConfigDrawer>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
