// @generated by Metrics Storybook story generator
// @source-hash: 5f9ebb8592c01300

import type { Meta, StoryObj } from "@storybook/react-vite";

import { ContextMenu } from "./context-menu";

const meta = {
  title: "Primitives/Ui Core/Context Menu",
  component: ContextMenu,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ContextMenu>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
