// @generated by Metrics Storybook story generator
// @source-hash: c7b429470e655842

import type { Meta, StoryObj } from "@storybook/react-vite";

import { CopyCode } from "./copy-code";

const meta = {
  title: "Primitives/Ui Core/Copy Code",
  component: CopyCode,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {
    code: "Code",
  },
} satisfies Meta<typeof CopyCode>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
