// @generated by Metrics Storybook story generator
// @source-hash: c6aed2b846ee29cb

import type { Meta, StoryObj } from "@storybook/react-vite";

import { DatePicker } from "./date-picker";

const meta = {
  title: "Primitives/Ui Core/Date Picker",
  component: DatePicker,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof DatePicker>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
