// @generated by Metrics Storybook story generator
// @source-hash: 5010569587e9b706

import type { Meta, StoryObj } from "@storybook/react";

import { TwentyThreeFour } from "./day-picker";

const meta = {
  title: "Primitives/Ui Core/Twenty Three Four",
  component: TwentyThreeFour,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof TwentyThreeFour>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
