// @generated by Metrics Storybook story generator
// @source-hash: 4bba5733e59783ca

import type { Meta, StoryObj } from "@storybook/react";

import { Dialog } from "./dialog";

const meta = {
  title: "Primitives/Ui Core/Dialog",
  component: Dialog,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof Dialog>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
