// @generated by Metrics Storybook story generator
// @source-hash: 3d06171d400b99ef

import type { Meta, StoryObj } from "@storybook/react-vite";

import { DirectionProvider } from "./direction";

const meta = {
  title: "Primitives/Ui Core/Direction Provider",
  component: DirectionProvider,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof DirectionProvider>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
