// @generated by Metrics Storybook story generator
// @source-hash: a9ba76db1949e171

import type { Meta, StoryObj } from "@storybook/react";

import { Drawer } from "./drawer";

const meta = {
  title: "Primitives/Ui Core/Drawer",
  component: Drawer,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof Drawer>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
