// @generated by Metrics Storybook story generator
// @source-hash: de7209a62babc8e2

import type { Meta, StoryObj } from "@storybook/react";

import { EditSwitch } from "./edit-switch";

const meta = {
  title: "Primitives/Ui Core/Edit Switch",
  component: EditSwitch,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {
    defaultEditing: false,
    onCheckedChange: () => {},
  },
} satisfies Meta<typeof EditSwitch>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
