// @generated by Metrics Storybook story generator
// @source-hash: 39334c80d18e7920

import type { Meta, StoryObj } from "@storybook/react-vite";

import { Empty } from "./empty";

const meta = {
  title: "Primitives/Ui Core/Empty",
  component: Empty,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof Empty>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
