// @generated by Metrics Storybook story generator
// @source-hash: 50a39c5f659bcf15

// TODO(story): Provide representative values for required props:
// - filters: Filter<T>[]
// - fields: FilterFieldsConfig<T>
import type { Meta, StoryObj } from "@storybook/react-vite";

import { FiltersContent } from "./filters";

const meta = {
  title: "Primitives/Ui Core/Filters Content",
  component: FiltersContent,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {
    onChange: () => {},
  },
} satisfies Meta<typeof FiltersContent>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
