// @generated by Metrics Storybook story generator
// @source-hash: c2159197eebdabfa

import type { Meta, StoryObj } from "@storybook/react";

import { Group } from "./group";

const meta = {
  title: "Primitives/Ui Core/Group",
  component: Group,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {
    children: "Group",
  },
} satisfies Meta<typeof Group>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
