// @generated by Metrics Storybook story generator
// @source-hash: e67e82f5458d2e51

import type { Meta, StoryObj } from "@storybook/react";

import { HoverCard } from "./hover-card";

const meta = {
  title: "Primitives/Ui Core/Hover Card",
  component: HoverCard,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof HoverCard>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
