// @generated by Metrics Storybook story generator
// @source-hash: 41c0b1fe36702174

import type { Meta, StoryObj } from "@storybook/react-vite";

import { HoverCardSides } from "./hover-card-sides";

const meta = {
  title: "Primitives/Ui Core/Hover Card Sides",
  component: HoverCardSides,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof HoverCardSides>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
