// @generated by Metrics Storybook story generator
// @source-hash: e41c85e3ddd15268

import type { Meta, StoryObj } from "@storybook/react";

import { Item } from "./item";

const meta = {
  title: "Primitives/Ui Core/Item",
  component: Item,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof Item>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
