// @generated by Metrics Storybook story generator
// @source-hash: 7633aea25a53b815

import type { Meta, StoryObj } from "@storybook/react";

import { Kbd } from "./kbd";

const meta = {
  title: "Primitives/Ui Core/Kbd",
  component: Kbd,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof Kbd>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
