// @generated by Metrics Storybook story generator
// @source-hash: 626d9dc49c729f59

import type { Meta, StoryObj } from "@storybook/react";

import { NativeSelect } from "./native-select";

const meta = {
  title: "Primitives/Ui Core/Native Select",
  component: NativeSelect,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof NativeSelect>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
