// @generated by Metrics Storybook story generator
// @source-hash: 8db4b99797a6e0d3

import type { Meta, StoryObj } from "@storybook/react";

import { NavigationMenu } from "./navigation-menu";

const meta = {
  title: "Primitives/Ui Core/Navigation Menu",
  component: NavigationMenu,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof NavigationMenu>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
