// @generated by Metrics Storybook story generator
// @source-hash: 5bd7d02534cc4a8d

import type { Meta, StoryObj } from "@storybook/react-vite";

import { NumberField } from "./number-field";

const meta = {
  title: "Primitives/Ui Core/Number Field",
  component: NumberField,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof NumberField>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
