// @generated by Metrics Storybook story generator
// @source-hash: e3671a963cd67339

import type { Meta, StoryObj } from "@storybook/react-vite";

import { PreviewCardTrigger } from "./preview-card";

const meta = {
  title: "Primitives/Ui Core/Preview Card Trigger",
  component: PreviewCardTrigger,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof PreviewCardTrigger>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
