// @generated by Metrics Storybook story generator
// @source-hash: 9d3ee2577fad4ba6

// TODO(story): Provide representative values for required props:
// - products: Product[]
import type { Meta, StoryObj } from "@storybook/react-vite";

import { ProductGrid } from "./product-grid";

const meta = {
  title: "Primitives/Ui Core/Product Grid",
  component: ProductGrid,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {
    categories: "Categories",
  },
} satisfies Meta<typeof ProductGrid>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
