// @generated by Metrics Storybook story generator
// @source-hash: 916c22af70fccf20

import type { Meta, StoryObj } from "@storybook/react-vite";

import { Promo } from "./promo";

const meta = {
  title: "Primitives/Ui Core/Promo",
  component: Promo,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {
    title: "Title",
    description: "Description",
    buttonText: "Button Text",
    buttonLink: "Button Link",
    backgroundImage: "Background Image",
  },
} satisfies Meta<typeof Promo>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
