// @generated by Metrics Storybook story generator
// @source-hash: 56bd14ff2d276a25

import type { Meta, StoryObj } from "@storybook/react-vite";

import { RadioGroup } from "./radio-group";

const meta = {
  title: "Primitives/Ui Core/Radio Group",
  component: RadioGroup,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof RadioGroup>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
