// @generated by Metrics Storybook story generator
// @source-hash: f66f56f10ff3b3ed

import type { Meta, StoryObj } from "@storybook/react-vite";

import { Rating } from "./rating";

const meta = {
  title: "Primitives/Ui Core/Rating",
  component: Rating,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof Rating>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
