// @generated by Metrics Storybook story generator
// @source-hash: 848adff8eb62fc0d

import type { Meta, StoryObj } from "@storybook/react";

import { ResizablePanelGroup } from "./resizable";

const meta = {
  title: "Primitives/Ui Core/Resizable Panel Group",
  component: ResizablePanelGroup,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ResizablePanelGroup>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
