// @generated by Metrics Storybook story generator
// @source-hash: 9e4ab2f4f7477c3a

import type { Meta, StoryObj } from "@storybook/react";

import { Sheet } from "./sheet";

const meta = {
  title: "Primitives/Ui Core/Sheet",
  component: Sheet,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof Sheet>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
