// @generated by Metrics Storybook story generator
// @source-hash: cc30ef9293b09a69

import type { Meta, StoryObj } from "@storybook/react-vite";

import { Toaster } from "./sonner";

const meta = {
  title: "Primitives/Ui Core/Toaster",
  component: Toaster,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof Toaster>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
