// @generated by Metrics Storybook story generator
// @source-hash: 374c4efb868167da

import type { Meta, StoryObj } from "@storybook/react";

import { SortableTableHead } from "./sortable-table-head";

const meta = {
  title: "Primitives/Ui Core/Sortable Table Head",
  component: SortableTableHead,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof SortableTableHead>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
