// @generated by Metrics Storybook story generator
// @source-hash: 4f2725596d85aacd

import type { Meta, StoryObj } from "@storybook/react";

import { Spinner } from "./spinner";

const meta = {
  title: "Primitives/Ui Core/Spinner",
  component: Spinner,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof Spinner>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
