// @generated by Metrics Storybook story generator
// @source-hash: a355cffbb3b3b6ae

import type { Meta, StoryObj } from "@storybook/react";

import { ToastProvider } from "./toast";

const meta = {
  title: "Primitives/Ui Core/Toast Provider",
  component: ToastProvider,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ToastProvider>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
