// @generated by Metrics Storybook story generator
// @source-hash: c3f7323d6faa0606

import type { Meta, StoryObj } from "@storybook/react-vite";

import { ToggleGroup } from "./toggle-group";

const meta = {
  title: "Primitives/Ui Core/Toggle Group",
  component: ToggleGroup,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof ToggleGroup>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
