// @generated by Metrics Storybook story generator
// @source-hash: feda74de7d594876

import type { Meta, StoryObj } from "@storybook/react-vite";

import { TooltipPopup } from "./tooltip";

const meta = {
  title: "Primitives/Ui Core/Tooltip Popup",
  component: TooltipPopup,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof TooltipPopup>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
