// @generated by Metrics Storybook story generator
// @source-hash: 521d87f7e1d5b593

import type { Meta, StoryObj } from "@storybook/react-vite";

import { MenubarIcons } from "./menubar-icons";

const meta = {
  title: "Primitives/Menus/Menubar Icons",
  component: MenubarIcons,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof MenubarIcons>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
