// @generated by Metrics Storybook story generator
// @source-hash: a0ec795813332724

import type { Meta, StoryObj } from "@storybook/react-vite";

import { Particle } from "./menu-other";

const meta = {
  title: "Primitives/Menus/Menu Other",
  component: Particle,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof Particle>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
