// @generated by Metrics Storybook story generator
// @source-hash: e74338eaab7dfc6f

import type { Meta, StoryObj } from "@storybook/react";

import { MenuTrigger } from "./menu";

const meta = {
  title: "Primitives/Menus/Menu Trigger",
  component: MenuTrigger,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof MenuTrigger>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
