// @generated by Metrics Storybook story generator
// @source-hash: 15f36a15b4e3049d

import type { Meta, StoryObj } from "@storybook/react";

import { MenubarCheckbox } from "./menubar-checkbox";

const meta = {
  title: "Primitives/Menus/Menubar Checkbox",
  component: MenubarCheckbox,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof MenubarCheckbox>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
