// @generated by Metrics Storybook story generator
// @source-hash: e536126a7114d45a

import type { Meta, StoryObj } from "@storybook/react";

import { MenubarRadio } from "./menubar-radio";

const meta = {
  title: "Primitives/Menus/Menubar Radio",
  component: MenubarRadio,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof MenubarRadio>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
