// @generated by Metrics Storybook story generator
// @source-hash: dfef7206ed2d9b8f

import type { Meta, StoryObj } from "@storybook/react";

import { MenubarSubmenu } from "./menubar-submenu";

const meta = {
  title: "Primitives/Menus/Menubar Submenu",
  component: MenubarSubmenu,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof MenubarSubmenu>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
