// @generated by Metrics Storybook story generator
// @source-hash: b5863b37740aaa4e

import type { Meta, StoryObj } from "@storybook/react";

import { Menubar } from "./menubar";

const meta = {
  title: "Primitives/Menus/Menubar",
  component: Menubar,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof Menubar>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
