// @generated by Metrics Storybook story generator
// @source-hash: f0c19d3c108ee496

import type { Meta, StoryObj } from "@storybook/react";

import { NavigationMenu } from "./navigation-menu";

const meta = {
  title: "Primitives/Menus/Navigation Menu",
  component: NavigationMenu,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
  },
  args: {},
} satisfies Meta<typeof NavigationMenu>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
